### ISSUE TITLE
$uiRoute on an <a> is not compatible with <a ui-sref> links. 

### ISSUE THREAD

**Issue by dymk** [angular-ui/ui-utils#100]
I'm using ui-router 0.0.2 on ~master, and ui-utils 0.0.4. `$uiRoute` on anchor tags does not work if the anchor tag is deriving its `href` from a `ui-sref`. 

For example, this _will_ work as expected: 
```html
<a ui-route ng-href="#/home" ng-class="{selected: $uiRoute}">Home</a>
```
And "Home" will have the `selected` class when the user is at the location `/#/home`. 

The following will not work: 
```html
<a ui-route ui-sref="home" ng-class="{selected: $uiRoute}">Home</a>
```

When the user locates to the route that corresponds to `$state.go("home")` (which is ui-router specific), the `selected` class is not applied to the link. 

The error thrown is: 
```Error: uiRoute missing a route or href property on <the anchor tag>```

**Comment by PowerKiKi** [comment]
UI.Utils modules was split in individuals repositories. If still valid, please consider re-submitting the issue on its dedicated issue tracker.

See the [README for details](https://github.com/angular-ui/ui-utils#readme).
