### ISSUE TITLE
Karma config file is broken; can't run tests

### ISSUE THREAD

**Issue by dymk** [angular-ui/ui-utils#101]
As per the readme.md file, I've run the following commands: 

1. ```npm install -g karma grunt-cli bower```
2. ```npm install```
3. ```bower install```

However, running: 

```karma start --browsers=Chrome,Firefox test/karma.conf.js --single-run=true```
fails with

```
$ karma start --browsers=Chrome,Firefox test/karma.conf.js --single-run=true
WARN [config]: JASMINE is not supported anymore.
        Please use `frameworks = ["jasmine"];` instead.
WARN [config]: JASMINE_ADAPTER is not supported anymore.
        Please use `frameworks = ["jasmine"];` instead.
WARN [config]: LOG_INFO is not supported anymore.
  Please use `karma.LOG_INFO` instead.
ERROR [config]: Config file must export a function!
  module.exports = function(config) {
    config.set({
      // your config
    });
  };
```

Windows 7 x64 bit, Node v. 0.10.17, Karma version 0.10.2

**Comment by PowerKiKi** [comment]
UI.Utils modules was split in individuals repositories. If still valid, please consider re-submitting the issue on its dedicated issue tracker.

See the [README for details](https://github.com/angular-ui/ui-utils#readme).
