### ISSUE TITLE
Hover intent directive

### ISSUE THREAD

**Issue by marklagendijk** [angular-ui/ui-utils#106]
Hey guys,
I just wrote an 'hoverIntent' directive. This is an 'hover' eventhandler which fires after the user has hovered an element for a given amount of time (and doesn't fire if the user stops hovering that element within that time).
Since this is an quite common feature, I was wondering if you would be interested in adding this to ui-utils. If you are I can write an pull request for it (including tests).

Code of the directive:
``` js
angular.module('MyApp.directives')
	.directive('hoverIntent', ['$timeout', function($timeout){
		return {
			restrict: 'A',
			link: function(scope, element, attributes){
				var hoverIntentPromise;
				element.bind('mouseenter', function(event){
					var delay = scope.$eval(attributes.hoverIntentDelay);
					if(delay === undefined){
						delay = 500;
					}

					hoverIntentPromise = $timeout(function(){
						scope.$eval(attributes.hoverIntent, { $event: event });
					}, delay);
				});
				element.bind('mouseleave', function(){
					$timeout.cancel(hoverIntentPromise);
				});
			}
		};
	}]);
```

Usage example (an menu which opens after an intended hover):
``` js
<ul id="mainMenu" ng-class="{ open: mainMenuOpen }" hover-intent="mainMenuOpen = true" ng-mouseleave="mainMenuOpen = false">
```

**Comment by PowerKiKi** [comment]
UI.Utils modules was split in individuals repositories. If still valid, please consider re-submitting the issue on its dedicated issue tracker.

See the [README for details](https://github.com/angular-ui/ui-utils#readme).

**Comment by ghost** [comment]
When using this directive, I include the following lines in the appropriate places:
element.addClass('hover') 
element.removeClass('hover')

It allows elements to be easily styled in CSS using the hoverIntent directive:
.class:hover { } becomes
.class.hover { }
