### ISSUE TITLE
IE10, ui-mask, and placeholder

### ISSUE THREAD

**Issue by tommyk** [angular-ui/ui-utils#114]
In IE10, having ui-mask and placeholder attributes on an input causes the form to become dirty and the input to become invalid if it has required / ng-required.  Please see the following fiddler as an example, view it in  both IE10 and chrome to see the difference.

http://jsfiddle.net/tommmyk/Ekc2J/

After digging around, I found that this line in the the initializeElement method is causing a random 'input' event to be fired, followed by a 'focus' event.  I don't quite understand what is causing this, so if anyone knows please let me know!
```
iElement.attr('placeholder', maskPlaceholder);
```

I replaced it with to fix my problem (still unit tests failing in IE10, not related to this fix)
```
if (!iElement.attr('placeholder') || iElement.attr('placeholder') != maskPlaceholder) {
      iElement.attr('placeholder', maskPlaceholder);
}
```

**Comment by PowerKiKi** [comment]
UI.Utils modules was split in individuals repositories. If still valid, please consider re-submitting on its dedicated repository: https://github.com/angular-ui/ui-mask

See the [README for details](https://github.com/angular-ui/ui-utils#readme).
