### ISSUE TITLE
Asynchronous validation broken with Angular 1.2.0-rc2

### ISSUE THREAD

**Issue by andreas-gruenbacher** [angular-ui/ui-utils#120]
For asynchronous validation, the expression bassed to ui-validate is supposed to return a promise. The ui.validate module uses scope.$eval to evaluate expressions. Unfortunately, since this commit:
  https://github.com/angular/angular.js/commit/3a65822023119b71deab5e298c7ef2de204caa13

Angular no longer allows promises to be returned from $eval.

Also discussed here:
  https://github.com/angular-ui/angular-ui-OLDREPO/issues/257

Also, ui-tools are missing a test case for asynchronous validation.

**Comment by PowerKiKi** [comment]
UI.Utils modules was split in individuals repositories. If still valid, please consider re-submitting on its dedicated repository: https://github.com/angular-ui/ui-validate

See the [README for details](https://github.com/angular-ui/ui-utils#readme).
