### ISSUE TITLE
ui.route does not work with $locationProvider.hashPrefix set

### ISSUE THREAD

**Issue by dmitryevseev** [angular-ui/ui-utils#127]
uiRoute directive does not work if app uses: `$locationProvider.hashPrefix("!");`

It's because of this condition: ` if ((hash = newVal.indexOf('#')) > -1) {`

**Comment by PowerKiKi** [comment]
UI.Utils modules was split in individuals repositories. If still valid, please consider re-submitting the issue on its dedicated issue tracker.

See the [README for details](https://github.com/angular-ui/ui-utils#readme).
