### ISSUE TITLE
ui-mask, disable validation

### ISSUE THREAD

**Issue by mdedetrich** [angular-ui/ui-utils#139]
Is there currently an option to prevent ui-mask from running validation (in other words, just to provide masking and not do any validation.

I am trying to use ui-mask with my own custom validation (using the validation guide provided here http://docs.angularjs.org/guide/forms). Although the validation itself works when you add for '_' to account for how ui-mask works, the value returned by the validation is always set by ui-mask, I wan't the return value of the validation to be set by my own validator

The personal use case is pretty simple, I have a date in an input field which is the form 99-99-9999. I however want to use my own validator (a wrapper around moment.js) to actually check if the date is valid. Furthermore, my own validator actually returns a date object (which is stored in the ngModel). If I try to use ui-mask when combined with my validator, although it uses my validator, the variable that ends up getting returned to the model ends up being a string, not a date object

**Comment by PowerKiKi** [comment]
UI.Utils modules was split in individuals repositories. If still valid, please consider re-submitting on its dedicated repository: https://github.com/angular-ui/ui-mask

See the [README for details](https://github.com/angular-ui/ui-utils#readme).

**Comment by mabdulhalim** [comment]
just add "?" like `ui-mask="(?9?9?9) ?9?9?9?9-?9?9?9?9" `
