### ISSUE TITLE
Currency mask for unlimited digits

### ISSUE THREAD

**Issue by gh-naylor** [angular-ui/ui-utils#143]
How would I go about creating a mask for the following?

9.99
99.99
9,999
9,999.99
9,999,999
9,999,999.99
etc.

**Comment by PowerKiKi** [comment]
UI.Utils modules was split in individuals repositories. If still valid, please consider re-submitting on its dedicated repository: https://github.com/angular-ui/ui-mask

See the [README for details](https://github.com/angular-ui/ui-utils#readme).
