### ISSUE TITLE
ui-mask feature request add reverse order

### ISSUE THREAD

**Issue by blowsie** [angular-ui/ui-utils#144]
It would be nice if the mask could fill the value in reverse order.

Example of desired functionality can be seen here.
http://www.meiocodigo.com/projects/meiomask/

This would open the utility up to further functionality like decimal support.

**Comment by PowerKiKi** [comment]
UI.Utils modules was split in individuals repositories. If still valid, please consider re-submitting on its dedicated repository: https://github.com/angular-ui/ui-mask

See the [README for details](https://github.com/angular-ui/ui-utils#readme).
