### ISSUE TITLE
Need examples of using jQuery Passthrough

### ISSUE THREAD

**Issue by vkelman** [angular-ui/ui-utils#148]
"How" part of jQuery Passthrough documentation looks pretty cryptic for inexperienced AngularJS developers like myself. If you Google for "examples of using jQuery Passthrough" you'll see that there is a lot of confusion. It would be nice if you could provide more examples on using jQuery Passthrough with different jQuery plugins, demonstrating each possibility described in your text,

"To pass parameters use the ui-options attribute. The value will be evaluated in the $scope context and passed to the function. If defaults are set, the passed options will extend them. If a string is passed, the default options will be ignored.

Use the directive name jq for namespacing inside uiJqConfig. Then sub-namespace options for each function by the name of that function (exactly as it is passed to ui-jq)"

**Comment by PowerKiKi** [comment]
UI.Utils modules was split in individuals repositories. If still valid, please consider re-submitting the issue on its dedicated issue tracker.

See the [README for details](https://github.com/angular-ui/ui-utils#readme).
