### ISSUE TITLE
bower main property not valid

### ISSUE THREAD

**Issue by pajooh** [angular-ui/ui-utils#157]
i use ui-utils via bower, and the modules folder is not included in bower
so, ``` "main": "./modules/utils.js" ``` is not valid

**Comment by PowerKiKi** [comment]
UI.Utils modules was split in individuals repositories. If still valid, please consider re-submitting the issue on its dedicated issue tracker.

See the [README for details](https://github.com/angular-ui/ui-utils#readme).
