### ISSUE TITLE
multiple validators per model

### ISSUE THREAD

**Issue by axelav** [angular-ui/ui-utils#163]
I'm trying to check a few different parameters of a password to ensure its validated state.

```
<input type="password" name="userPassword" ng-model="user.password" ng-minlength="8" ui-validate="{uppercase : 'passwordHasUppercaseLetter($value)', lowercase: 'passwordHasLowercaseLetter($value)', number: 'passwordHasNumber($value)'}" required>
<div ng-show="resetPasswordForm.userPassword.$dirty && resetPasswordForm.userPassword.$invalid">
    <span class="help-block" ng-show="resetPasswordForm.userPassword.$error.required">Please enter your password.</span>
    <span class="help-block" ng-show="resetPasswordForm.userPassword.$error.minlength">Your password should be at least eight characters.</span>
    <span class="help-block" ng-show="resetPasswordForm.userPassword.$error.uppercase">Your password should contain at least one uppercase letter.</span>
    <span class="help-block" ng-show="resetPasswordForm.userPassword.$error.lowercase">Your password should contain at least one lowercase letter.</span>
    <span class="help-block" ng-show="resetPasswordForm.userPassword.$error.number">Your password should contain at least one number.</span>
</div>
```

In my controller, I validate with the following:

```
$scope.passwordHasUppercaseLetter = function(value) {
  return (value != null) && /[A-Z]/.test(value);
};

$scope.passwordHasLowercaseLetter = function(value) {
  return (value != null) && /[a-z]/.test(value);
};

$scope.passwordHasNumber = function(value) {
  return (value != null) && /\d/.test(value);
};
```

This *almost* works but you have to fulfill each requirement in its declared order for it to work correctly. For the code above, the password would have to start with "Aa4....." in order to behave correctly. Entering "4bC...." will only clear all three requirements after the uppercase letter has been entered into the input. 

Is there any way to have all three validations resolve independent of the order in which they're declared?

**Comment by PowerKiKi** [comment]
UI.Utils modules was split in individuals repositories. If still valid, please consider re-submitting on its dedicated repository: https://github.com/angular-ui/ui-validate

See the [README for details](https://github.com/angular-ui/ui-utils#readme).
