### ISSUE TITLE
ui-scrollfix breaks after navigating between views

### ISSUE THREAD

**Issue by jtammen** [angular-ui/ui-utils#165]
I am using the ```ui-scrollfix``` directive in my app and observed that it stops working when navigating between different views (using plain Angular ```$routeProvider```). After a bit of debugging I think this is caused by the fact that ```elm[0].offsetTop``` seems to return "incorrect" values during the time the directive is being applied (after having navigated to another view).

Has anybody else experienced that behavior and knows how to circumvent it?

Don't know whether this is a problem with this directive or rather the way I am structuring my pages, so [I created a sample app](https://github.com/jtammen/angular-ui-utils-scrollfix-issue) that demonstrates the problem.

**Comment by PowerKiKi** [comment]
UI.Utils modules was split in individuals repositories. If still valid, please consider re-submitting the issue on its dedicated repository: https://github.com/angular-ui/ui-scrollpoint

See the [README for details](https://github.com/angular-ui/ui-utils#readme).
