### ISSUE TITLE
ui-validate-watch should allow deep watch of model object

### ISSUE THREAD

**Issue by lacmyers** [angular-ui/ui-utils#166]
$watch has an optional third parameter, objectEquality, which specifies whether to "Compare object for equality rather than for reference". ui-validate-watch should provide a way to set this to support more complicated validation scenarios.

**Comment by PowerKiKi** [comment]
UI.Utils modules was split in individuals repositories. If still valid, please consider re-submitting on its dedicated repository: https://github.com/angular-ui/ui-validate

See the [README for details](https://github.com/angular-ui/ui-utils#readme).
