### ISSUE TITLE
ui-mask does not handle 0 as integer

### ISSUE THREAD

**Issue by jeverden** [angular-ui/ui-utils#168]
When a number mask is passed to the directive and 0 as a integer is passed the ng-model it clears the input. If 0 is a string the values still displays.

http://plnkr.co/edit/sII1hKod5CqbgzPGCiiL?p=preview

**Comment by PowerKiKi** [comment]
UI.Utils modules was split in individuals repositories. If still valid, please consider re-submitting on its dedicated repository: https://github.com/angular-ui/ui-mask

See the [README for details](https://github.com/angular-ui/ui-utils#readme).
