### ISSUE TITLE
Update to Angular 1.2

### ISSUE THREAD

**Issue by quicksnap** [angular-ui/ui-utils#176]
I attempted to fork ui-validate in order to provide support for `$watchCollection` as `ui-watch-collection`. Then I found ui-utils is not at v1.2 (which `$watchCollection` needs)

Updating ui-utils breaks the tests. Is there an upgrade timeline? Accepting pull requests for that?

**Comment by PowerKiKi** [comment]
UI.Utils modules was split in individuals repositories. If still valid, please consider re-submitting the issue on its dedicated issue tracker.

See the [README for details](https://github.com/angular-ui/ui-utils#readme).
