### ISSUE TITLE
Mask Placeholder usage is not following usual

### ISSUE THREAD

**Issue by antonioribeiro** [angular-ui/ui-utils#181]
Angular-UI mask is using the placeholder to show the mask, so if I do 

```
<div ng-controller="myController">
    <input type="text"
        ng-model="date"
        ui-mask="99/99/9999"
        placeholder="Birth Date"/>  
</div>
```

I will show the input fileld as 

```
+--------------+
| Bi/th/Date   |
+--------------+
```

And not

```
+--------------+
| Birth Date   |
+--------------+
```

And after the focus (or even a hover) is set to the input it should change to:

```
+--------------+
| __/__/____   |
+--------------+
```

Not trying to compare anything here, but Twitter Boostrap uses the placeholder this way and so does jquery.inputmask: https://github.com/RobinHerbots/jquery.inputmask. This last one changes from 'Birth Date' to the mask as soon as you hover the input.

**Comment by grushikhin** [comment]
+1

**Comment by mrniko** [comment]
+1

**Comment by kontrollanten** [comment]
+1

**Comment by PowerKiKi** [comment]
PR #353 is trying to solve this issue

**Comment by sean-roberts** [comment]
I want to write something like this: <input placeholder="Arbitrary Field Helper" ui-mask="***-***" />

I don't care about masking the placeholder at all, so it would be FAR more beneficial to opt out of placeholder masking period. I don't think #353 is going to help with that.

**Comment by xtreemrage** [comment]
+1

**Comment by iclems** [comment]
+1 ;)

**Comment by jlubeck** [comment]
+1

**Comment by AndrewEastwood** [comment]
+1

**Comment by AndrewEastwood** [comment]
when it's gonna be fixed?

**Comment by PowerKiKi** [comment]
@AndrewEastwood when somebody care enough to take time to write tests and documentation for #353

**Comment by PowerKiKi** [comment]
UI.Utils modules was split in individuals repositories. If still valid, please consider re-submitting on its dedicated repository: https://github.com/angular-ui/ui-mask

See the [README for details](https://github.com/angular-ui/ui-utils#readme).
