### ISSUE TITLE
Error when used with ui-validate

### ISSUE THREAD

**Issue by edriang** [angular-ui/ui-utils#188]
When you have a masked input with an ui-validate function sometimes ui-validate returns false even if the masked input is correct.

For example:
Mask: 999-9999

If you type, for example, 213-5334 everything its ok, but if you type 8 (or more) characters, the last character you type is also sent to the validator function (in this case, 9 numbers instead of 8)

**Comment by DmitryEfimenko** [comment]
Had the same problem. Adding `priority: 1000` to the `uiValidate` directive solves the issue.

**Comment by PowerKiKi** [comment]
UI.Utils modules was split in individuals repositories. If still valid, please consider re-submitting on its dedicated repository: https://github.com/angular-ui/ui-mask

See the [README for details](https://github.com/angular-ui/ui-utils#readme).
