### ISSUE TITLE
UI-Mask bad cursor placement

### ISSUE THREAD

**Issue by accolver** [angular-ui/ui-utils#189]
The cursor changes position (resets to beginning) when switching browser tabs.

Steps: 
1. ui-mask for phone
     Ex.  An input field with data-ui-mask="(999) 999 – 9999"
2. Focus on input (cursor is denoted by pipe | )
     (|___) ___ - ____
3. Change browser tabs then return. Cursor has moved.
     |(___) ___ - ____
4. Typing the phone number (123) 456 - 7890 now looks like (234) 567 - 8901

Other events (other than switching browser tabs) may trigger the issue.

**Comment by newenegue** [comment]
I have this same issue with inputs masks on a Galaxy S3.  I am using backbone.js and creating my own input masks for phone numbers in this format: XXX-XXX-XXXX

My solution was to use the backbone "keyup" event to call my input formatting function.  Previously, the event was listing to "input".  I'm not really sure how the "input" event works, but changing that solved my issues.

**Comment by mtotheikle** [comment]
@newenegue you care to share a gist of what you did?

**Comment by newenegue** [comment]
@mtotheikle 

Originally, I used the follow:

```
Backbone.View.extend({
  ...
  events: {
    "input #phoneInput": "onPhoneChange"
  },
  ...
});
```

Changing `input` to `keyup` fixed my cursor placement on the Galaxy S3 (native browser):

```
Backbone.View.extend({
  ...
  events: {
    "keyup #phoneInput": "onPhoneChange"
  },
  ...
});
```

I hope this helps!

**Comment by PowerKiKi** [comment]
UI.Utils modules was split in individuals repositories. If still valid, please consider re-submitting on its dedicated repository: https://github.com/angular-ui/ui-mask

See the [README for details](https://github.com/angular-ui/ui-utils#readme).

**Comment by ralfius** [comment]
```
const uiMaskConfigProvider = $injector.get('uiMask.ConfigProvider');
uiMaskConfigProvider.eventsToHandle(['keypress', 'keyup', 'click', 'focus']);
```

helped for me within app run block
