### ISSUE TITLE
ui-mask stops working after $compile($element)($scope)

### ISSUE THREAD

**Issue by pocesar** [angular-ui/ui-utils#192]
If I have a custom directive that applies ui-mask to the element depending on their class, on the linking function, when I do a `$compile($element)($scope)` the ui-mask directive stops working. 

```coffee
angular.module('tel', ['ui.mask'])
  .directive('tel', ['$compile', ($compile)->
    {
      restrict: 'A'
      require: 'ngModel'
      compile: (element, attrs) ->
        celMask = false

        if attrs.tel is 'true'
          celMask = true
          element.attr('ui-mask', '{{mask}}')
        else
          element.attr('ui-mask', '(99) 9999-9999')

        element.removeAttr('tel')
        element.removeAttr('data-tel')

        ($scope, $element, $attrs, controller) ->
          if celMask
            $scope.mask = '(99) 9999-9999'

          $compile($element)($scope)

          return
    }
  ])
```

```html
<input type="tel" data-tel id="billing:telefone" ng-model="Ctrl.user.telefone">
```

the typed numbers aren't appearing (and the model isn't changing). I'm using Angular.js 1.2.13, jQuery 1.11.0 and latest angular-ui-utils from bower

**Comment by PowerKiKi** [comment]
UI.Utils modules was split in individuals repositories. If still valid, please consider re-submitting on its dedicated repository: https://github.com/angular-ui/ui-mask

See the [README for details](https://github.com/angular-ui/ui-utils#readme).
