### ISSUE TITLE
ui-validate flipping the validation function's output

### ISSUE THREAD

**Issue by CMCDragonkai** [angular-ui/ui-utils#193]
It seems that when using ui-validate. It's flipping the returned booleans.

For example, using this on an input element.

```
ui-validate="{validUrl: 'validateUrl($value)'}"
```

If validateUrl($value) returns true, validUrl ends up being false and vice versa. This seems a bit counter intuitive. I would expect that the validUrl would be true if the validateUrl($value) returned true. The docs also seem to agree on this.

I was testing on the latest ui-utils, just console logging the outputs of the function and the validUrl.

**Comment by PowerKiKi** [comment]
UI.Utils modules was split in individuals repositories. If still valid, please consider re-submitting on its dedicated repository: https://github.com/angular-ui/ui-validate

See the [README for details](https://github.com/angular-ui/ui-utils#readme).
