### ISSUE TITLE
ui-refresh with jq-ui="buttonset"  causing 'cannot call methods on button prior to initialization' exception

### ISSUE THREAD

**Issue by jamie-pate** [angular-ui/ui-utils#196]
Due to the dynamic nature of angularjs and ng-repeat the buttonset contents would sometimes be modified. Once the ui-jq directive called $(elm).buttonset('refresh') (via the ui-refresh mechanism) it would throw **cannot call methods on button prior to initialization; attempted to call method 'widget'**

After much research I determined that the radioGroup() function was not checking to make sure that all the buttons it found were in fact buttons before calling jqueryui methods on them.

My work-around simply removes the constraint via Monkey-patching:

```
(function($) {
    'use strict';
    var orig_button = $.fn.button;
    $.fn.button = function(options) {
        if (!$(this).is(':ui-button')) {
            orig_button.call(this);
        }
        orig_button.call(options);
    };
})(jQuery);
```
I also filed a bug with jquery ui here: http://bugs.jqueryui.com/ticket/9842
but I have been unable to reproduce this bug by hand.
(my efforts so far are here: http://jsfiddle.net/34Cpk/3/ )

**Comment by PowerKiKi** [comment]
UI.Utils modules was split in individuals repositories. If still valid, please consider re-submitting the issue on its dedicated issue tracker.

See the [README for details](https://github.com/angular-ui/ui-utils#readme).
