### ISSUE TITLE
$uiRoute ancestry

### ISSUE THREAD

**Issue by ajwhite** [angular-ui/ui-utils#205]
Is there any way to have child routes utilize $uiRoute?

EG:

- products<br/>
---view<br/>
---edit

Say we are on the edit page, and we have a root navigation node for 'products'. How, using $uiRoute, can the navigation element know that it's child is the current state? Must this be done with a custom directive?

**Comment by PowerKiKi** [comment]
UI.Utils modules was split in individuals repositories. If still valid, please consider re-submitting the issue on its dedicated issue tracker.

See the [README for details](https://github.com/angular-ui/ui-utils#readme).
