### ISSUE TITLE
ui.mask input.focus()

### ISSUE THREAD

**Issue by Coobaha** [angular-ui/ui-utils#207]
when triggering input.focus() - ui.mask immediately triggers blur, so cursor blinks on input and then focus out triggers.

In my case, after submitting form I wanted to focus first invalid input with ui-mask directive. 

If I click and hold submit button for a sec - blur events triggers first, after mousedown release  element got focused like it should.

**Comment by PowerKiKi** [comment]
UI.Utils modules was split in individuals repositories. If still valid, please consider re-submitting on its dedicated repository: https://github.com/angular-ui/ui-mask

See the [README for details](https://github.com/angular-ui/ui-utils#readme).
