### ISSUE TITLE
Multiple ui-scrollfix on the same page

### ISSUE THREAD

**Issue by hajarasoahaingo** [angular-ui/ui-utils#208]
I want to use two **ui-scrollfix**, the first works well, but the second adds the **ui-scrollfix** class as soon as i begin to scroll.

I'm using *version v0.0.4 - 2013-09-08*

**Comment by PowerKiKi** [comment]
UI.Utils modules was split in individuals repositories. If still valid, please consider re-submitting the issue on its dedicated repository: https://github.com/angular-ui/ui-scrollpoint

See the [README for details](https://github.com/angular-ui/ui-utils#readme).
