### ISSUE TITLE
(ui.keypress) bind to $document

### ISSUE THREAD

**Issue by maxbates** [angular-ui/ui-utils#217]
I'd like to attach listeners to the document itself, using the parsing provided by the $keypress service, and the ability to unbind a listener on a particular scope's destruction (e.g. so you could declare it in a controller for a particular page, and remove it on navigating away from page).

This could look like `$keypress.on(mode, actions, $scope)`

I have achieved such functionality but it required modifying the factory directly. Could you please either: 

1) Separate out the action and key-event parsing into it's own service
2) Support binding to the $document (described below)

-- 

In my case, I created a service `$keypress` with `.on()` and `.off()`, which bound to the `$document` using a signature described above. In the ui.keypress factory, I modified the code by setting up a simple check:

````javascript
if (elm == $document) {
   params = attrs;
}
````
moving the function in `elem.bind()` to a variable called `handler` so it could be unbound, and removing the binding on destruction of the passed scope:

````javascript
scope.$on('$destroy', function() {
    elm.unbind(mode, handler);
});
````

**Comment by PowerKiKi** [comment]
UI.Utils modules was split in individuals repositories. If still valid, please consider re-submitting the issue on its dedicated issue tracker.

See the [README for details](https://github.com/angular-ui/ui-utils#readme).
