### ISSUE TITLE
showHide multiple Elements

### ISSUE THREAD

**Issue by bondero** [angular-ui/ui-utils#218]
I would like to toggle multiple elements on a page but all independent from each other. the ng-click="showHide=!showHide" method currently toggles all ui-toggle="showHide" elements even though it should only toggle the next element.

Is this possible with the current implementation or would that be an extra feature?

**Comment by PowerKiKi** [comment]
UI.Utils modules was split in individuals repositories. If still valid, please consider re-submitting the issue on its dedicated issue tracker.

See the [README for details](https://github.com/angular-ui/ui-utils#readme).
