### ISSUE TITLE
Error on undefined string when using highlight

### ISSUE THREAD

**Issue by eikaramba** [angular-ui/ui-utils#221]
When i use the highlight filter, but i have an undefined string (e.g. i want to highlight fields from an user object from the server, but maybe this user has no address field) then an error is thrown. Not really crucial, but i would add a short check not only for search but also for the text parameter, in order to avoid those errors.

**Comment by PowerKiKi** [comment]
UI.Utils modules was split in individuals repositories. If still valid, please consider re-submitting the issue on its dedicated issue tracker.

See the [README for details](https://github.com/angular-ui/ui-utils#readme).
