### ISSUE TITLE
Highlight breaks if filtered string contains HTML

### ISSUE THREAD

**Issue by shaneedwards** [angular-ui/ui-utils#223]
I threw together this jsfiddle (http://jsfiddle.net/4FxZ7/1/) to demonstrate.  I used the same demonstration from your site except I wrapped the 'thank you' at the end of the filtered string in a < strong > tag.  The highlight still works, but it throws a slew of errors to the console because the HTML sanitizer can't parse the broken HTML tags the highlighter creates.

To reproduce, go to http://jsfiddle.net/4FxZ7/1/ and search for 'thank'.  As soon as you hit the first character it will throw an error like this: 

Error: [$sanitize:badparse] The sanitizer was unable to parse the following block of html: <s<span class="ui-match">t</span>rong><span class="ui-match">t</span>hank you</s<span class="ui-match">t</span>rong>.

**Comment by PowerKiKi** [comment]
UI.Utils modules was split in individuals repositories. If still valid, please consider re-submitting the issue on its dedicated issue tracker.

See the [README for details](https://github.com/angular-ui/ui-utils#readme).
