### ISSUE TITLE
jQuery Passthrough load plugin on partial load (use uiRefresh ?)

### ISSUE THREAD

**Issue by jamez14** [angular-ui/ui-utils#227]
I had a quick question in regards to **jQuery PassThrough** and specifically **uiRefresh**. When I navigate to a partial view (with my custom jQuery plugin on it) - is there a way to load this plugin on page load? Because currently it does not load when navigating from one partial view to the "plugin" view. If I reload the page w/ my plugin on it, the plugin will load with no problem. Is this is a job for **uiRefresh** Here's my plugin if it helps... https://github.com/jamez14/TrailFinder/blob/master/app/js/map.js

**Comment by PowerKiKi** [comment]
UI.Utils modules was split in individuals repositories. If still valid, please consider re-submitting the issue on its dedicated issue tracker.

See the [README for details](https://github.com/angular-ui/ui-utils#readme).
