### ISSUE TITLE
Functions defined inside linking function - bad for performance?

### ISSUE THREAD

**Issue by dmitriz** [angular-ui/ui-utils#231]
I wonder why some functions are defined inside the linking function of directives.
For instance, the function `isDatasource`. Isn't it bad for performance?

**Comment by PowerKiKi** [comment]
UI.Utils modules was split in individuals repositories. If still valid, please consider re-submitting the issue on its dedicated issue tracker.

See the [README for details](https://github.com/angular-ui/ui-utils#readme).
