### ISSUE TITLE
When combining angular-ui validate with regular angular validation, incorrect result

### ISSUE THREAD

**Issue by rocketraman** [angular-ui/ui-utils#241]
I am using the "password confirmation" validation functionality of angular-ui validate. This works fine, until I add a second validation on the "password" field `ng-minlength=...`. Once this second validation is added, the password confirmation validate starts incorrectly reporting that the passwords do not match even if they do, as long as the length validation is failing. Once the length validation passes, then and only then does ui-validate correctly set the $error result as well.

**Comment by PowerKiKi** [comment]
UI.Utils modules was split in individuals repositories. If still valid, please consider re-submitting on its dedicated repository: https://github.com/angular-ui/ui-validate

See the [README for details](https://github.com/angular-ui/ui-utils#readme).
