### ISSUE TITLE
ui-validate doesn't correctly update ng-model

### ISSUE THREAD

**Issue by ffesseler** [angular-ui/ui-utils#25]
I've made a quick demo with 2 inputs. 
My form should be valid if input 1 value length is shorter than input 2 value.

It looks like when my validation function return false, ng-model from input 1 is not set anymore.

http://plnkr.co/edit/GP4FbX1m4Q37hULQzMPt?p=preview

(Just type something in the first input, ng-model (myText1) doesn't change)

**Comment by PowerKiKi** [comment]
UI.Utils modules was split in individuals repositories. If still valid, please consider re-submitting on its dedicated repository: https://github.com/angular-ui/ui-validate

See the [README for details](https://github.com/angular-ui/ui-utils#readme).

**Comment by danday74** [comment]
You need to add ng-model-options="{allowInvalid:true}" to your form input elements to stop this happening - the problem is that when a promise is rejected (e.g. using $q or $http) the model, by default, is not updated. Crazy huh! Cost me a day working this out.
