### ISSUE TITLE
[ui.keypress] provide a way to reevaluate the keymap expression

### ISSUE THREAD

**Issue by jrencz** [angular-ui/ui-utils#250]
In my use case I have to bind 2 slightly different key maps, but the ui-keypress directive argument gets evaluated only once on when the link function is called.
Do you have any interest in enabling value watching for the directives?

**Comment by PowerKiKi** [comment]
UI.Utils modules was split in individuals repositories. If still valid, please consider re-submitting the issue on its dedicated issue tracker.

See the [README for details](https://github.com/angular-ui/ui-utils#readme).
