### ISSUE TITLE
ngScroll does not see datasource declared on $scope

### ISSUE THREAD

**Issue by dukehoops** [angular-ui/ui-utils#251]
uiScroll [docs](https://github.com/angular-ui/ui-utils/tree/master/modules/scroll#data-source)  say:

"The directive will locate the object using the provided data source name. It will first look for a property with the given name on its $scope. If none found it will try to get an angular service with the provided name."

When I try to declare a `datasource` on a `$scope` I get an 'unknown provider' error indicating that the directive did not find a DS on scope and went on to try and load it as an injectible dependency (failing since the latter does not exist).

I think this is a timing issue caused by the fact that uiScroll looks for `$scope.datasource` in its' [`link()`](https://github.com/angular-ui/ui-utils/blob/master/modules/scroll/scroll.js#L45), which executes ahead of any parent directive's `link()`. For example my directive, assigned to a DOM element that is  a parent of element with  `ngScroll`, declares `$scope.datasource = {....}` in its' `link()'`. 

AFAIK in AngularJS, the sequence of compile/link fn execution is:
1) parent element directive compile()
2) child element ngScroll compile()
3) child link()
4) parent link()
[...see here for details](http://stackoverflow.com/a/21410877/182808)

In the given situation, datasource is declared in step 4) but the check happens earlier in 3).

I think `$scope.datasource` [check](https://github.com/angular-ui/ui-utils/blob/master/modules/scroll/scroll.js#L45) should be done in a `$watch` expression instead of directly in ngScroll `$link()`.

**Comment by jfuehner** [comment]
@dhilt I get this same error when trying to use ui-scroll within a directive declaring the datasource on the directives scope. Any thoughts or workarounds?

**Comment by dhilt** [comment]
@jfuehner I have a draft of wiki-documentation on the ui.scroll component and there are two links which can help you:
* [a description of "Datasource on scope" sample](https://github.com/dhilt/NGScroller/wiki/ui.scroll-samples-wiki#sample4)
* [some page with datasource implementation samples](https://github.com/dhilt/NGScroller/wiki/Datasource)

I understand that there is some difference between ctrl's scope and directives's scope but in my projects I have no problems in both cases, and without a living demo of your problem (jsfiddle etc) this is all I can do for you...
