### ISSUE TITLE
Karma Tests fail in angular 1.2.11

### ISSUE THREAD

**Issue by CGowdy** [angular-ui/ui-utils#252]
I'm trying to write karma tests for my project and i'm having issues getting the tests to work.  I am using angular 1.2.11 and karma 0.12.4 with Jasmine 2.0 and karma-jasmine 0.2.2.

The biggest issue I have with the example tests is .trigger() is used to test keypress and that isn't a supported function for jqLite.

When I updated it to triggerHandler() it appears as though nothing happens...like the keypress event either doesn't fire or the page elements don't recognize the keypress.

**Comment by PowerKiKi** [comment]
UI.Utils modules was split in individuals repositories. If still valid, please consider re-submitting the issue on its dedicated issue tracker.

See the [README for details](https://github.com/angular-ui/ui-utils#readme).
