### ISSUE TITLE
IE 11 bad positioning...

### ISSUE THREAD

**Issue by mdelgadov** [angular-ui/ui-utils#254]
Boy! 
This one is evident: 
In IE 11, go to the demo page http://angular-ui.github.io/ui-utils/

- Go to the ui-mask demo...

- define a mask (easiest: click any button, (999)999-9999 for example)

- Enter any number on the "Masked Input" field
- Move to any other field and then tab back to the "Masked Input" field
- Instead of selecting the whole field, it moves one space forward, allowing for entering wrong information.
![untitled](https://cloud.githubusercontent.com/assets/1537551/3188980/b1b95b7a-ecbf-11e3-9796-0859269d562b.png)

**Comment by PowerKiKi** [comment]
UI.Utils modules was split in individuals repositories. If still valid, please consider re-submitting on its dedicated repository: https://github.com/angular-ui/ui-mask

See the [README for details](https://github.com/angular-ui/ui-utils#readme).
