### ISSUE TITLE
ui-date + ui-mask error

### ISSUE THREAD

**Issue by eduardolagares** [angular-ui/ui-utils#26]
When I use the directive with ui ui-date-mask, to make the blur event, the following error occurs:

Error: $apply already in progress

This error points to the directive ui-date, when the blur event is fired: angular-ui.js line 271

I think this one $apply simultaneous occurring in ui-date and in-mask.

**Comment by PowerKiKi** [comment]
UI.Utils modules was split in individuals repositories. If still valid, please consider re-submitting on its dedicated repository: https://github.com/angular-ui/ui-mask

See the [README for details](https://github.com/angular-ui/ui-utils#readme).
