### ISSUE TITLE
does ui-mask suport number format currency

### ISSUE THREAD

**Issue by calebeaires** [angular-ui/ui-utils#262]
Is there any way to make ui-mask suport number format currency like: 

(more number as user type) 999.999,99

I have used the diretive above, but when typing, on zero shows between numbers.

<pre>

app.directive('numberFormat', function ($filter) {
    var precision = 2;
    return {
        require: 'ngModel',
        link: function (scope, element, attrs, ctrl) {
            ctrl.$formatters.push(function (data) {
                console.log(data)
                var formatted = $filter('currency')(data, "");
                //convert data from model format to view format
                return formatted; //converted
            });
            ctrl.$parsers.push(function (data) {
                var plainNumber = data.replace(/[^\d|\-+|\+]/g, '');
                var length = plainNumber.length;
                var intValue = plainNumber.substring(0,length-precision);
                var decimalValue = plainNumber.substring(length-precision,length)
                var plainNumberWithDecimal = intValue + '.' + decimalValue;
                //convert data from view format to model format
                var formatted = $filter('currency')(plainNumberWithDecimal, "");
                element.val(formatted);   
                return Number(plainNumberWithDecimal);
            });
        }
    };
});

</pre>

**Comment by PowerKiKi** [comment]
UI.Utils modules was split in individuals repositories. If still valid, please consider re-submitting on its dedicated repository: https://github.com/angular-ui/ui-mask

See the [README for details](https://github.com/angular-ui/ui-utils#readme).
