### ISSUE TITLE
i propose ui-validate-watch value deep watch option

### ISSUE THREAD

**Issue by dbwhddn10** [angular-ui/ui-utils#266]
i suggestion ui-validate-watch value deep watch option.

like this.

http://stackoverflow.com/questions/14712089/how-to-deep-watch-an-array-in-angularjs

i hope to change from http://jsfiddle.net/dbwhddn10/GNJP4/1/ to http://jsfiddle.net/dbwhddn10/GNJP4/2/

and i recommand a article http://teropa.info/blog/2014/01/26/the-three-watch-depths-of-angularjs.html

**Comment by PowerKiKi** [comment]
UI.Utils modules was split in individuals repositories. If still valid, please consider re-submitting on its dedicated repository: https://github.com/angular-ui/ui-validate

See the [README for details](https://github.com/angular-ui/ui-utils#readme).
