### ISSUE TITLE
UI Mask bug

### ISSUE THREAD

**Issue by max258** [angular-ui/ui-utils#268]
When the Placeholder is set as placeholder="" the mask cannot be done.

Next issue:
In mask cannot be declared only some symbols as: +, -
It would be super define some symbols in array.

**Comment by PowerKiKi** [comment]
UI.Utils modules was split in individuals repositories. If still valid, please consider re-submitting on its dedicated repository: https://github.com/angular-ui/ui-mask

See the [README for details](https://github.com/angular-ui/ui-utils#readme).
