### ISSUE TITLE
mask doesn't work with Angular's default input type="number"

### ISSUE THREAD

**Issue by rayshan** [angular-ui/ui-utils#27]
Hello. I tried an input field with `type="number"` and `mask="99%"` with bootstrap styling. The appearance works correctly but I cannot type in any value, the `ng-model`'s value predefined in controller doesn't show up.

The reason for using `type="number"` is for the convenience of min/max/required.
http://docs.angularjs.org/api/ng.directive:input.number

Any ideas?

**Comment by armyofda12mnkeys** [comment]
I'd be interested in a fix for this as well. We use (999) 999-9999 masking for phone #'s on our contact pages and they don't work correctly on mobile if its a type="number" field.

**Comment by zachcarroll** [comment]
has anyone found a solution for setting up a mask for input type=number?

**Comment by armyofda12mnkeys** [comment]
anyone try type=tel? i think that helped my masking on phones, esp Android which uses keyboard autocomplete when its another field. and type=number shows up kinda ugly for desktop (while tel gives the numberpad on mobile, and on desktop doesn't do that number field whose browser UI 'number-incrementer' may not work with textfield masking)

**Comment by cleiton-tavares** [comment]
It is using tel on the input type, worked well and the way I would if usase number, thank @armyofda12mnkeys

**Comment by PowerKiKi** [comment]
Closing since there is a workaround

**Comment by lstone** [comment]
I'd like to recommend this be reopened. Using type 'tel' is inappropriate for accessibility users.

**Comment by ingoncalves** [comment]
I agree with Istone and suggest that this Issue be reopened, since the workaround is not appropriate.

**Comment by ProLoser** [comment]
Based on https://github.com/plentz/jquery-maskmoney/issues/80 and https://github.com/igorescobar/jQuery-Mask-Plugin/issues/25 the general consensus seems to be to not use `type=number` for fields you wish to mask. If your concern is accessibility then perhaps using @rayshan's solution is better?

I'm on the fence about re-opening this issue because I don't know how to solve it.

**Comment by PowerKiKi** [comment]
This is project is now obsolete, please continue the discussion, if need be, over there: https://github.com/angular-ui/ui-mask so that the project maintainer can pitch in too.
