### ISSUE TITLE
ui mask generating "0" when backspace

### ISSUE THREAD

**Issue by unruledboy** [angular-ui/ui-utils#271]
set the mask to "0499-999-999", input numbers like "0412-345-678", then start to press "backspace" from the end, after reaching "04", you will see it starts to append "0", end up like "0400-000-000"

**Comment by AntonVodyanoy** [comment]
Тоже с толкнулся с такой проблемой, использовал маски ui-mask="FSAAAAAAAA" and ui-mask="+7(999)999-99-99" и при нажатии backspace в самом начале строки происходило увеличение значения на первый символ из маски, 
исправил переписав вот так функцию:
```javascript
function unmaskValue(value){
            var valueUnmasked = '',
              maskPatternsCopy = maskPatterns.slice();
            // Preprocess by stripping mask components from value
            value = value.toString();
            value=value.replace(/_/g,'');
            angular.forEach(maskComponents, function (component){
                if(value.length<component.length){
                    value='';
                }
              value = value.replace(component, '');
            });
            angular.forEach(value.split(''), function (chr){
              if (maskPatternsCopy.length && maskPatternsCopy[0].test(chr)) {
                valueUnmasked += chr;
                maskPatternsCopy.shift();
              }
            });
            return valueUnmasked;
          }
```

**Comment by PowerKiKi** [comment]
UI.Utils modules was split in individuals repositories. If still valid, please consider re-submitting on its dedicated repository: https://github.com/angular-ui/ui-mask

See the [README for details](https://github.com/angular-ui/ui-utils#readme).
