### ISSUE TITLE
UI Mask - Placeholder

### ISSUE THREAD

**Issue by victorkurauchi** [angular-ui/ui-utils#273]
UI Mask works well without placeholder.

If i put an empty placeholder, it doesn't work. 
If i put a placeholder, the mask is not applicable.

1) no way

    <input type="text" placeholder="" class="input-nome-med" ng-model="sac.cpf" ui-mask='999.999.999-99' required>

2) strange behavior/mask doesnt apply

    <input type="text" placeholder="CPF" class="input-nome-med" ng-model="sac.cpf" ui-mask='999.999.999-99' required>

I know the first item is already a known issue. But the second i face it just now.
Is there some catch to that ?

Thanks!

**Comment by jlubeck** [comment]
This is a big problem and I see it's been a year since this was bugged... no one else is having an issue with this odd behaviour?

**Comment by PowerKiKi** [comment]
Closing as duplicates of https://github.com/angular-ui/ui-utils/issues/181
