### ISSUE TITLE
Suggestion: Add all modules to bower.json

### ISSUE THREAD

**Issue by chrisnicola** [angular-ui/ui-utils#274]
The way this is setup to use a different branch per modules is unnecessary. The `main` property can list each module file and people can include the modules they want as needed. 

I can't think of any reason to have a separate build per module.

This also makes the modules usable for tools like rails-assets that rely on bower.json. I've created my own fork to get this to work with rails-assets so you can see what I mean here:

https://github.com/chrisnicola/ui-utils/blob/master/bower.json

**Comment by csmosx** [comment]
+1 considering I thought that's what you meant in the docs about installing from the #bower branch... that it would install all the individual modules. Not real sure what that line is instructing then...

**Comment by PowerKiKi** [comment]
If we were to change that, what would happen for existing project using the current structure ?

**Comment by chrisnicola** [comment]
I would suggest keeping the branches in their current state and deprecating them.

**Comment by csmosx** [comment]
Yes, freeze the module branches, perhaps after adding a DEPRECATED file with instructions to move to a non-branched install for latest.

Continue the bower branch (and version tags derived from it) as is structured, just add all the module js files to it.

This way you are only adding to and not subtracting from existing projects who update.

The instructions for install should be:
```
bower install angular-ui-utils
```

And only for those who want the latest (unstable):
```
bower install angular-ui-utils#bower
```

**Comment by NickTomlin** [comment]
I am :+1: on this. I currently using just one module, which works great with the `bower-<modulename>` branch, but I want to include another. My only options right now are to include _all_ the modules, or point to `#master` and manually include a module.

**Comment by PowerKiKi** [comment]
I am not sure who could decide on this, since it could impact a lot of people...

But it would take some work to adapt build system (Travis does most of the work). So I guess this definitely won't happen unless one of you submit a PR.

@ProLoser, @douglasduteil you seem the be the two with the most contributions in this repository. Any opinion on this subject ?

**Comment by douglasduteil** [comment]
Hi @PowerKiKi  good to see that you're still active on this repo.
The current build system is the most flexible in my opinion.

<br>

@NickTomlin Adding two modules is farly easy with manual namespacing on the bower.json

```js
{
  "name": "myBowerModule",
  "version": "0.0.0",
  "dependencies": {
    "angular-ui-utils-mask": "angular-ui-utils#bower-mask",
    "angular-ui-utils-format": "angular-ui-utils#bower-format"
  }
}
```

Following https://github.com/angular-ui/ui-utils/issues/180#issuecomment-34321874

<br>

@chrisnicola @csmosx Using all the ui-utils sub-modules at ones is the rare case for me. But the default release for it. `bower install angular-ui-utils`

<br>

PS: @PowerKiKi It's might be good to add those info to the README.md what you thinks ?
PS: @PowerKiKi To work correctly when you want to release a new version you're suppose to tag the actual sources on the master with a tag `srcX.Y.Z` (see https://github.com/angular-ui/ui-utils/releases/tag/src0.1.1) then Travis it doing the rest (see https://github.com/angular-ui/ui-utils/releases/tag/v0.1.1) ?

**Comment by LeleDev** [comment]
It's really annoying that you can't install multiple modules instead of the complete library. Please fix this soon...

**Comment by ProLoser** [comment]
Honestly I've been slightly toying with the idea of splitting this repo up.

Theoretically, you could still have an 'umbrella' repo that simply is 1 bower file with a bunch of bower dependencies on the other repos, and it just contains `ui.utils` module and depends on all the other modules. This would be closer to Angular today, and feels less chaotic than bower branches, but may end up cluttering the AngularUI namespace(?).

Thoughts?

**Comment by ProLoser** [comment]
Also, specifically curious about @douglasduteil's thoughts on this proposal since he put such an awesome amount of work into the existing build system ^

**Comment by PowerKiKi** [comment]
I wouldn't oppose splitting project (and dropping obsolete one). ui-scroll is already [half splitted](https://github.com/angular-ui/ui-utils/issues/232#issuecomment-77638569). And I have to agree that while the automated build system is awesome, the branches generated are quite confusing for newcomers.

**Comment by PowerKiKi** [comment]
UI.Utils modules was split in individuals repositories. Those repositories are now published on npm and bower. However not all modules were considered interesting enough to be kept. See the [README for details](https://github.com/angular-ui/ui-utils#readme).
