### ISSUE TITLE
ui-scrollfix does not work correctly after dynamic content

### ISSUE THREAD

**Issue by ygotthilf** [angular-ui/ui-utils#287]
Hi,

ui-scrollfix does not work when dynamic content (ng-repeat for example) is loaded before this directive.

Here a sample : http://codepen.io/ygotthilf/pen/FABhk

I think the top position of the directive should be feched in the scroll listener and not once in the link function. 

Regards,

Yoann

**Comment by stephennancekivell** [comment]
+1, thanks @ygotthilf thats how I expect it to work.

**Comment by jwebcat** [comment]
is this fix merged in currently to stable release?

**Comment by PowerKiKi** [comment]
@jwebcat, yes [v0.2.2](https://github.com/angular-ui/ui-utils/releases/tag/v0.2.2) was just released.
