### ISSUE TITLE
bower install bower install angular-ui-utils does not work

### ISSUE THREAD

**Issue by leachjustin18** [angular-ui/ui-utils#290]
When running this command, it returns: 

bower not-cached    git://github.com/theshock/atomjs.git#*
bower resolve       git://github.com/theshock/atomjs.git#*
bower cached        git://github.com/angular-ui/ui-utils.git#0.1.1
bower validate      0.1.1 against git://github.com/angular-ui/ui-utils.git#*
bower checkout      bower#master
bower invalid-meta  bower is missing "main" entry in bower.json
bower invalid-meta  bower is missing "ignore" entry in bower.json
bower resolved      git://github.com/theshock/atomjs.git#474cdf1ee5
bower ENOTFOUND     Package install not found

**Comment by NickTomlin** [comment]
@leachjustin18 is this still an issue for you? I'm able to install via `bower install angular-ui-utils` without problems.

**Comment by PowerKiKi** [comment]
Closing for now, re-open if it happens again
