### ISSUE TITLE
ui.scroll

### ISSUE THREAD

**Issue by char0n** [angular-ui/ui-utils#296]
Hello,

I have been testing ui.scroll for a couple of hours now. And I need some help with it I guess. If you could help me, I would really appreciate it. These are my points/questions to ui.scroll:

1.) Events

I couldn't find any documentation for events. I have a use cases where I need to remove/add from/to datasource. Eventually in a source code I found 'insert.item' event listener. In my application when I add new attachment, this attachment is broadcasted with 'insert.item' event into scroll.js like this:

$rootScope.$broadcast('insert.item', 1, attachment);

Unfortunately this doesn't work. This is the line that causes the issue:

https://github.com/angular-ui/ui-utils/blob/master/modules/scroll/scroll.js#L556

This code only works for $rootScope.$broadcast('insert.item', n, attachment); n >= 2

Is this a bug, or is this intentional, and the most important question, is this the right way to add newly created items to datasource or should I use reivision mechanism ?

Thanks

**Comment by pelizza** [comment]
This fix doesn't worked for me. I'm just able to add items after the second position, as mentioned above.
How about you @char0n?

**Comment by char0n** [comment]
@pelizza I completly switched to http://binarymuse.github.io/ngInfiniteScroll/. Sorry cannot help you now ;]

**Comment by mfeingold** [comment]
The event based API for scroll updates was never documented and will be removed in the future. For now you can use the revision method on the datasource, or you can wait another couple of days for the new API to be published. See also #291
