### ISSUE TITLE
Remove Older / Useless Features

### ISSUE THREAD

**Issue by ProLoser** [angular-ui/ui-utils#297]
I think we should remove some stuff that never really added a lot of improvement or have since become exceedingly obsolete.

* ui-reset
* inflector
* ui-show/ui-hide
* ui-scrollfix
* highlight(?)
* unique(?)
* format(?)
* ui-include(?)

I think the major version number would have to be bumped. Does anyone have any huge objections to this? All of these were added VERY early in Angular's lifetime and I think they were too personal to really reuse now.

**Comment by RopoMen** [comment]
Hi,
atm. I'm not using any of these, but in one project I have been doing replacement of "bootstrap.js" jquery based features into AngularUI Bootstrap directives which are pure Angular. But it is missing replacement for Bootstrap affix, atleast what I have been looking...

So this "scrollfix" would be almost the replacement for "affix" if it would provide a service with callbacks. And or, it would provide a way to add certain css class for element when scrolling has passed it.

Example:
<div class="navbar navbar-default" ui-scrollfix="200" ui-scrollfix-class="navbar-fixed-top"></div>

**Comment by PowerKiKi** [comment]
Actual code base of ui-scroll is in https://github.com/Hill30/NGScroller. Please re-submit your issue over there if needed.
