### ISSUE TITLE
Make unique always accept angular expressions

### ISSUE THREAD

**Issue by aidanhs** [angular-ui/ui-utils#30]
As per comment on https://github.com/angular-ui/ui-utils/pull/28#issuecomment-17778715

Unique (and other utilities?) do not currently accept arbitrary angular expressions. This might be desirable, hence this issue.

**Comment by PowerKiKi** [comment]
UI.Utils modules was split in individuals repositories. If still valid, please consider re-submitting the issue on its dedicated issue tracker.

See the [README for details](https://github.com/angular-ui/ui-utils#readme).
