### ISSUE TITLE
ui mask filter

### ISSUE THREAD

**Issue by isRuslan** [angular-ui/ui-utils#301]
It would be great to have `ui-mask`-like filter.
Example:

    {{1234567899 | mask: '(999) 999-9999'}} // -> (123) 456-7899

**Comment by fernandosouza** [comment]
+1

**Comment by genu** [comment]
+1

**Comment by jancel** [comment]
+1

**Comment by jancel** [comment]
Does anyone have a current solution or workaround for specifying this type of behavior?

**Comment by armyofda12mnkeys** [comment]
+1 as well. 
We would like to keep phone and date formatting when a user fills out this info on our contact form.

**Comment by PowerKiKi** [comment]
UI.Utils modules was split in individuals repositories. If still valid, please consider re-submitting on its dedicated repository: https://github.com/angular-ui/ui-mask

See the [README for details](https://github.com/angular-ui/ui-utils#readme).

**Comment by alexgoroshko** [comment]
I don't have an input for phone number and need just show to user masked phone number. Is there any solution? As far as I see you use model property to show it. Have anybody implemented a filter like: {{1234567899 | mask: '(999) 999-9999'}} // -> (123) 456-7899

**Comment by PowerKiKi** [comment]
@alexgoroshko this issue is closed and the repository deprecated. Please consider contributing to https://github.com/angular-ui/ui-mask instead, ideally with a PR.

**Comment by vinyoliver** [comment]
+1
