### ISSUE TITLE
ui-mask input has wrong caret position and inconsistent behavior between Chrome/Firefox and IE11

### ISSUE THREAD

**Issue by lukexggwp** [angular-ui/ui-utils#302]
There are two issues I've encountered so far:
ISSUE 1: 
Browsers ( IE11, Chrome, Firefox )
Steps to reproduce:

  1) Complete the mask by filling in all text for the mask
  2) Select/highlight all the text within the mask
  3) Hit the left arrow or the home key

  Result: The cursor moves all the way to the front, then moves over to the 2nd position of the 
  mask ![image](https://cloud.githubusercontent.com/assets/8883383/4390655/f323101a-43fe-11e4-9bf6-240490180470.png)

  Expected: Cursor should be in the beginning position rather than the 2nd.

ISSUE 2: 
Browsers (IE11)
Steps to reproduce
  1) Complete the mask by filling in all text for the mask
  2) Remove focus from the masked input
  3) Tab into the masked input

Result: The input is not highlighted like it is in Chrome and Firefox, but rather the cursor is just placed in the 2nd position of the mask.

Expected: The input should be highlighted to give consistency between Chrome, Firefox, and IE

http://jsfiddle.net/f26svnz0/2/
Related bug: #254

**Comment by jeffsheets** [comment]
It feels like this previous pull request was trying to address the same issue. But it appears it was closed and never merged in.
https://github.com/angular-ui/ui-utils/pull/224

I'm having the same issue where IE9 does not select all the text when the field is tabbed into.

**Comment by PowerKiKi** [comment]
UI.Utils modules was split in individuals repositories. If still valid, please consider re-submitting on its dedicated repository: https://github.com/angular-ui/ui-mask

See the [README for details](https://github.com/angular-ui/ui-utils#readme).
