### ISSUE TITLE
ui-scroll is broken from 1.13 rc0 and beyond

### ISSUE THREAD

**Issue by Alexsey** [angular-ui/ui-utils#305]
As far as I can see problem is in https://github.com/angular-ui/ui-utils/blob/master/modules/scroll/scroll.js#L20 due to <a href='https://github.com/angular/angular.js/blob/master/CHANGELOG.md'>The returned value from directive controller constructors are now ignored</a>

Quick fix (very quick and ugly) is to replace
```
return element;
```
with
```
angular.extend(this, element);
```
and than in line 70
```
viewport = controllers[0] || angular.element(window);
```
with
```
viewport = controllers[0] && controllers[0][0] || angular.element(window);
viewport = angular.element(viewport);
```

I'm sure it may be transform to something as quick but less ugly, but for now I don't have time for this :(

**Comment by mfeingold** [comment]
The fix merged in on Oct 1st
