### ISSUE TITLE
ui-mask + ng-list unexpected output

### ISSUE THREAD

**Issue by juanpujol** [angular-ui/ui-utils#31]
Is there any way to integrate both directives ui-mask and ng-list?

```html
<input type="text" ng-model="newAttr.period" placeholder="i.e. 1995 ~ 2000" ui-mask="9999 ~ 9999" ng-list="~">
```

This returns ["19992005"] but the expected result would be ["1999","2005"] as it works without the ui-mask directive.

Is there any solution to this at this time?

Thank you.

**Comment by PowerKiKi** [comment]
UI.Utils modules was split in individuals repositories. If still valid, please consider re-submitting on its dedicated repository: https://github.com/angular-ui/ui-mask

See the [README for details](https://github.com/angular-ui/ui-utils#readme).
