### ISSUE TITLE
[ui-events] How to decrease delay time

### ISSUE THREAD

**Issue by namminh2005** [angular-ui/ui-utils#314]
Hi,

I'm using ui-events to bind resize event to an div, but delay time between events seems too long (i guess ~500ms). Is it possible to decrease delay time? Or any replacement?

Thanks a lot!

**Comment by PowerKiKi** [comment]
UI.Utils modules was split in individuals repositories. If still valid, please consider re-submitting the issue on its dedicated issue tracker.

See the [README for details](https://github.com/angular-ui/ui-utils#readme).
