### ISSUE TITLE
ui-validate and ui.bootstrap.popover have a problem working together

### ISSUE THREAD

**Issue by iegorov** [angular-ui/ui-utils#316]
When i use popover when password confirm (http://angular-ui.github.io/ui-utils/#/validate), ui-validate does not work properly. Expression ui-validate=" '$value == user.password' " return false instead true. 
http://bit.ly/1ESpTWO

**Comment by PowerKiKi** [comment]
UI.Utils modules was split in individuals repositories. If still valid, please consider re-submitting on its dedicated repository: https://github.com/angular-ui/ui-validate

See the [README for details](https://github.com/angular-ui/ui-utils#readme).
