### ISSUE TITLE
UI mask Issue in IE11 Angular 1.3.0

### ISSUE THREAD

**Issue by VJ1243** [angular-ui/ui-utils#325]
ui mask is not triggered when one number from the input field. it gets fired from second delete.
Ex : input  (999) 999 9999 
       Delete one number : (999) 999 999 - still valid
       Delete second number : (999) 999 99 - Invalid.

 This is happening only in IE11 and with Angular latest version 
![uimask](https://cloud.githubusercontent.com/assets/7876511/5108834/d60f674e-6fd2-11e4-841d-40c81beff09a.jpg)

**Comment by PowerKiKi** [comment]
UI.Utils modules was split in individuals repositories. If still valid, please consider re-submitting on its dedicated repository: https://github.com/angular-ui/ui-mask

See the [README for details](https://github.com/angular-ui/ui-utils#readme).
