### ISSUE TITLE
[ui-validate] radio buttons

### ISSUE THREAD

**Issue by DmitryEfimenko** [angular-ui/ui-utils#326]
ui-validate does not work right on radio buttons (and probably checkboxes).
It correctly sets form as invalid (so the submit button will be disabled), but the error message will never be shown.

Example:
```
<form name="myform" novalidate>
    <input type="radio" name="myRadio" ng-model="myValue" value="0" >
    <input type="radio" name="myRadio" ng-model="myValue" value="1" ui-validate="{ aww: '$value != 1 || false' }" >
    <input type="radio" name="myRadio" ng-model="myValue" value="2" >

    <div ng-show="myform.myRadio.$error.aww">
        This will never show up! Even if second radio is selected - bug!
    </div>
    
    <button type="submit" ng-disabled="myform.$invalid" >
</form>
```

**Comment by PowerKiKi** [comment]
UI.Utils modules was split in individuals repositories. If still valid, please consider re-submitting on its dedicated repository: https://github.com/angular-ui/ui-validate

See the [README for details](https://github.com/angular-ui/ui-utils#readme).
