### ISSUE TITLE
Bug on ui-mask directive

### ISSUE THREAD

**Issue by igordelorenzi** [angular-ui/ui-utils#329]
When an user is editing a text input and type `~ (tilde char)` followed by digits (until the end of masked slots) and blur, then it turns to blank! The mask was set as `ui-mask="999.999.999-99"` and the tested browsers were Chrome and Safari running on OS X 10.9.5 (Mavericks). Yes, I know it's a very low priority bug, but I'm just letting you know.

**Comment by PowerKiKi** [comment]
UI.Utils modules was split in individuals repositories. If still valid, please consider re-submitting on its dedicated repository: https://github.com/angular-ui/ui-mask

See the [README for details](https://github.com/angular-ui/ui-utils#readme).
