### ISSUE TITLE
ui-validate doesn't prevent model update

### ISSUE THREAD

**Issue by marcdexet-cnrs** [angular-ui/ui-utils#338]
Behaviors between standard angularjs validation and ui-validate.
Standard validation prevent model update if they fail.

See this plnkr. http://embed.plnkr.co/kqc0JIoF4wqtwfUkFwUm/preview

We have two fields, name and age .
Both of them have standards validation required ng-minlength="2" ng-maxlength="3".
Only age have ui-validate age must be grosser or equal to 21

````
  $scope.ge21 = function(value) {
    var nb = parseInt(value);
    return nb >= 21;
  }
````
    
Type 18 as age and observe DATA below. 
You will see model is updated in spite of invalidity. It's not the case of standard validations.

**Comment by PowerKiKi** [comment]
UI.Utils modules was split in individuals repositories. If still valid, please consider re-submitting on its dedicated repository: https://github.com/angular-ui/ui-validate

See the [README for details](https://github.com/angular-ui/ui-utils#readme).
