### ISSUE TITLE
ui.uploader startUpload doesn´t return server response

### ISSUE THREAD

**Issue by dackyD** [angular-ui/ui-utils#346]
There is no way to get the response from the server after the upload is complete except for the information of the current file being uploaded. It would be nice to have the server response as well. But really nice utility. Thanks

**Comment by sndp-vrma** [comment]
In your uploader.js file, search for below code:

self.options.onCompleted(file);

We need to add response parameter, so replace above code with:

self.options.onCompleted(file, xhr.responseText);

Now, you can get this response in your upload.js by replacing

onCompleted: function(file) {

With: 

onCompleted: function(file, res) {

Thanks,
Sandeep

**Comment by realtica** [comment]
@dackyD Could you test the new commit?, thanks to @sndp-vrma for the solution.

**Comment by sndp-vrma** [comment]
I will provide few more enhancement to this plugin very soon. I am making to deal with promises also.
