### ISSUE TITLE
Publish to npm

### ISSUE THREAD

**Issue by kentcdodds** [angular-ui/ui-utils#347]
Would really love to get this published to npm so I can use it with webpack!

**Comment by DSpeichert** [comment]
+1 on that
It will also make it possible to include ui-utils on cdnjs.com, as they have only the ancient 0.1.1 version.

**Comment by dotch** [comment]
+1

**Comment by dansomething** [comment]
+1 Right now I'm having to do some ugly workarounds in order to use ui-utils on a project that only has NPM managed dependencies. We removed Bower a while ago in order to avoid managing deps in two different places on a Browserified project.

**Comment by austinpray** [comment]
+1 you can also have travis automatically publish it when there is a tagged release https://github.com/austinpray/asset-builder/blob/8e2f6c3560901ad5a312e405403f4d7b374ba96a/.travis.yml#L33

**Comment by PowerKiKi** [comment]
I have zero experience with publishing to npm, but if somebody submit a PR, or at least concise explanation, I would merge it.

**Comment by kentcdodds** [comment]
I'm not sure how your build stuff works, but you'll likely want to do your `npm release` as part of your build script after you've moved all the files around. See [this simple explination](https://gist.github.com/coolaj86/1318304) for how to do the actual publishing :-)

**Comment by robsimpkins** [comment]
Another +1 for publishing the latest version to NPM, please.

**Comment by suevalov** [comment]
+1. this dependency is the last one in our bower.json.

**Comment by sricc** [comment]
+1

**Comment by franky-continu** [comment]
+1 (We only use npm as builder and we don't like to install bower nor gulp nor grunt nor anything)

**Comment by csvan** [comment]
+1, there currently is an NPM release, but it is not being maintained.

https://www.npmjs.com/package/angular-ui-utils

**Comment by franky-continu** [comment]
You can install from the git repo with npm but of course is not a requirejs :-) module 
Franky Diaz-Trepat
Full Stack Engineer
+1 (720) 295-0592 / 401-1276
skype: franky.diaz.trepat
franky@continu.co

**Comment by tamsammyy** [comment]
+1 for NPM+Browsify project

**Comment by alexandernst** [comment]
You already have the `package.json` file. The only thing you need to do is run `npm publish`.

**Comment by mshwery** [comment]
aw not up-to-date on npm. major sadness. :frowning:

**Comment by PowerKiKi** [comment]
UI.Utils modules was split in individuals repositories. Those repositories are now published on npm and bower. However not all modules were considered interesting enough to be kept. See the [README for details](https://github.com/angular-ui/ui-utils#readme).

**Comment by kentcdodds** [comment]
Yay! Splitting it into smaller modules and publishing them to npm are both
awesome things! Thanks!

- Kent C. Dodds

(Sent from my mobile device, please forgive typos or brevity)

**Comment by franky-continu** [comment]
Amazing News Guys, thank you so much for all the awesome work
Franky Diaz-Trepat
Full Stack Engineer
+1 (720) 295-0592 / 401-1276
skype: franky.diaz.trepat
franky@continu.co

**Comment by austinpray** [comment]
👏👏👏

**Comment by franky-continu** [comment]
What happened with ui-scroll

**Comment by PowerKiKi** [comment]
@franky-continu see that post and following: https://github.com/angular-ui/ui-utils/pull/406#issuecomment-117404004

**Comment by PowerKiKi** [comment]
@franky-continu https://github.com/angular-ui/ui-scroll

**Comment by franky-continu** [comment]
Sweet I’m there now :-)
Franky Diaz-Trepat
Full Stack Engineer
+1 (720) 295-0592 / 401-1276
skype: franky.diaz.trepat
franky@continu.co
