### ISSUE TITLE
ui.mask Model is validated only after change

### ISSUE THREAD

**Issue by dimrsilva** [angular-ui/ui-utils#351]
I need to set the mask depending on a previous field.
So, I created a scope var to the mask definition, but the field is only validated after first interaction.

Here is an example: http://jsfiddle.net/y3py47ns/

Apparently, the model value needs to be updated for the validation works.
I did a little trick for that on my client code:
- change model value
- trigger `$scope.$apply()`
- restore model value
- trigger  `$scope.$apply()`

```
var original = $scope.modelValue;
$scope.modelValue = '';
$scope.$apply();
$scope.modelValue = doc;
$scope.$apply();
```

**Comment by PowerKiKi** [comment]
UI.Utils modules was split in individuals repositories. If still valid, please consider re-submitting on its dedicated repository: https://github.com/angular-ui/ui-mask

See the [README for details](https://github.com/angular-ui/ui-utils#readme).
