### ISSUE TITLE
UI-Mask remains $dirty when used inside of ng-repeat and form.$setPristine is called.

### ISSUE THREAD

**Issue by NateRedding** [angular-ui/ui-utils#352]
I created a [Plunker](http://run.plnkr.co/plunks/PKA5Vv61Zl3KdSwahpFj/). Change the field and hit 'Reset'. You will see the form and field stay dirty. Clicking a second time sets everything to $pristine properly. Interestingly enough, you don't actually have to change the field - just click Reset and the field and form will be marked dirty without even doing anything!

ng-repeat seems to have some weird behavior where it creates a new element temporarily when $setPristine is called. This causes ui-mask's initializeElement() to be called, which tries to avoid dirtying the form by setting $viewValue directly rather than using $setViewValue, but the form still seems to be dirty afterwards.

              function initializeElement(){
                ...
                iElement.val(viewValue);
                controller.$viewValue = viewValue;  // THIS LINE SEEMS TO DIRTY THE FORM
                // Not using $setViewValue so we don't clobber the model value and dirty the form
                // without any kind of user interaction.
              }

Commenting out the line marked in the code snippet above seems to fix the part of the problem with ng-repeat (the first click doesn't dirty the form anymore),  but it doesn't seem like a good fix. And, there is the problem of the form still being dirty after the first call to $setPristine() anyways. Even using the field outside of an ng-repeat seems to have a similar problem with $dirty being set after changing the field and then calling $setPristine(). It does not have the problem when not changing the field, however.

Note: This uses the 0.2.1 version of ui-mask modified slightly with the fix in #350 as we want clearOnBlur working properly.

FYI, for some reason I couldn't get the plunker to behave exactly the same as the code in my app... in my app, commenting out the above line seems to fix the problem entirely (still probably not a correct fix though).

**Comment by PowerKiKi** [comment]
UI.Utils modules was split in individuals repositories. If still valid, please consider re-submitting on its dedicated repository: https://github.com/angular-ui/ui-mask

See the [README for details](https://github.com/angular-ui/ui-utils#readme).
