### ISSUE TITLE
Validation pass-through

### ISSUE THREAD

**Issue by ZIJ** [angular-ui/ui-utils#357]
Hi,

I'm trying to use `ui-validate` in a custom directive, but validation logic is external to it. Is there a way to pass the expression through attributes so that it would be evaluated in parent scope? I tried the following approach, but the expression seems to be evaluated only once:

Using like this:
````html
<div my-directive my-validation="{ myRule : 'myController.myValidator(item)' }"></div>
````

In directive code:
````javascript
scope: {
    myValidation: '='
}
````

And in directive template:
````html
<input ng-model="myModel.name" ui-validate="myValidation"/>
````

**Comment by DanEEStar** [comment]
I have the exact same question and would be interested in a possible answer

**Comment by PowerKiKi** [comment]
UI.Utils modules was split in individuals repositories. If still valid, please consider re-submitting the issue on its dedicated issue tracker.

See the [README for details](https://github.com/angular-ui/ui-utils#readme).
