### ISSUE TITLE
How can I enforce the index passed to the get function?

### ISSUE THREAD

**Issue by lmessinger** [angular-ui/ui-utils#363]
Hi

I'm implementing a chat window. A user can scroll up to get the chat history. Then, say he enters a new chat message. How can I enforce the ui-scroll to jump to the end of the data? so that the chat message will be seen immediately.

and one can generalize this - how can one enforce the index that would be passed to the get function?

another option is to start the scroll at the end.

thanks very much for any idea?

thanks
Lior

**Comment by PowerKiKi** [comment]
Actual code base of ui-scroll is in https://github.com/Hill30/NGScroller. Please re-submit your issue over there if needed.
