### ISSUE TITLE
Credit Card Mask

### ISSUE THREAD

**Issue by Bana0615** [angular-ui/ui-utils#364]
When i use a credit card mask of ui-mask="9999 9999 9999 9999" it works great but i have a problem when people try to use amex cards because it is only 15 chars and not 16. How would i allow it to be 15 or 16 that way i can allow people to use amex cards also?

**Comment by PowerKiKi** [comment]
With current code it is not possible. Maybe you could try to surround everything with ``ng-if`` or ``ng-switch`` and select the carde type beforehand
