### ISSUE TITLE
IE 11 & Firefox Error: Object.keys: argument is not an Object

### ISSUE THREAD

**Issue by bogacg** [angular-ui/ui-utils#365]
While my form works fine on Chrome, in IE 11 I'm getting this error:
Object.keys: argument is not an Object
with trace:
at extend (http://localhost:2974/Scripts/angular.js:412:7)
at Anonymous function (http://localhost:2974/jsplugins/angular-ui-utils/mask.js:101:23)
at uiMaskLinkingFunction (http://localhost:2974/jsplugins/angular-ui-utils/mask.js:95:15)
I'm on latest master (b52c01d) and Angular 1.3.8 

On Firefox error is given as : "Object is not an object"

Any guesses why it happens?

**Comment by bogacg** [comment]
SOLVED:
I am using UI-Router and put clearOnBlur option to a scope variable which gets assigned in route view template like this (as described in pull request #164 ):
```
                <input class="form-control"
                       id="inputPhone"
                       name="inputPhone"
                       type="text"
                       required
                       ui-mask="(999) 999 9999"
                       ui-options="vm.uiOptions"
                       ng-model="vm.order.phoneNumber" />
 
```
Which is not so good practice because that ui-router view doesn't get loaded  before user gets to that view...so I fixed it by defining that option globally instead of in view. (again as described in second part of #164 )

```
app.config(["$provide", function($provide) {
    $provide.decorator("uiMaskConfig", ["$delegate", function($delegate) {
        $delegate.clearOnBlur = false;
        return $delegate;
    }]);
}]);
```

**Comment by cdroulers** [comment]
I'm experiencing this problem in IE11 as well. I've identified the problem here: https://github.com/angular-ui/ui-utils/blob/master/modules/mask/mask.js#L94

It seems to be merging the default options with the specified options manually instead of trusting angular.extend. I've just tested quickly and angular.extend works just fine in Angular 1.3.14.

I'm guessing this might be for backwards compatibility? I'll use @bogacg's workaround for now!

**Comment by hokkaido** [comment]
I got the same problem in IE11.

**Comment by PowerKiKi** [comment]
UI.Utils modules was split in individuals repositories. If still valid, please consider re-submitting on its dedicated repository: https://github.com/angular-ui/ui-mask

See the [README for details](https://github.com/angular-ui/ui-utils#readme).
