### ISSUE TITLE
failed to grunt build the phantomjs package

### ISSUE THREAD

**Issue by EnergeticPixels** [angular-ui/ui-utils#366]
I am working through AngularUI Development (Packt book - chapter2), and the author is trying to get us exposure to building an application (in particular AngularUI-Utils).  I am working on a Windows 7 platform with node 0.10.35 and npm 1.4.28. When grunt is building the utils package, I am getting an "errno: 50, code: 'EPERM" when grunt tries to build phantomjs@1.9.15.  Is there anyone else seeing this??  I am sort of a nOOb at this stuff (reason I am working through a book).
Tony

**Comment by PowerKiKi** [comment]
UI.Utils modules was split in individuals repositories. If still valid, please consider re-submitting the issue on its dedicated issue tracker.

See the [README for details](https://github.com/angular-ui/ui-utils#readme).
