### ISSUE TITLE
ui-uploader query parameters support

### ISSUE THREAD

**Issue by samy100** [angular-ui/ui-utils#368]
Currently uiUploader.startUpload only supports a file array and a url. Would be great to have the ability to pass query parameters on the request with the file itself. Useful in quite a few cases. For example as part of the options object we can pass {params:{ param1: 'foo' , param2: 'bar'}}. When the upload starts the url will be transform into /upload?param1=foo&param2=bar, including the file(s) in the payload. It would also be welcomed the ability to set custom headers (but that's for another time I guess). Great job, can't wait for this! Thanks.

For quite a bit, I've been using the approach described here: http://uncorkedstudios.com/blog/multipartformdata-file-upload-with-angularjs

**Comment by PowerKiKi** [comment]
UI.Utils modules was split in individuals repositories. If still valid, please consider re-submitting the issue on its dedicated issue tracker.

See the [README for details](https://github.com/angular-ui/ui-utils#readme).
