### ISSUE TITLE
Add ui-uploader documentation

### ISSUE THREAD

**Issue by ehmicky** [angular-ui/ui-utils#374]
ui-uploader module is not documented.

**Comment by PowerKiKi** [comment]
https://github.com/angular-ui/ui-utils/tree/master/modules/uploader

If you think more documentation would be appropriate, please open a PR.

**Comment by realtica** [comment]
@PowerKiKi do you know why the ui-uploader was removed from ui-utils page?

**Comment by PowerKiKi** [comment]
@realtica as far as I know it was never part of http://angular-ui.github.io/ui-utils/, because it does not have a ``demo/index.html`` but ``demo/demo.html`` instead.

But I just changed that, it should appear soon...
