### ISSUE TITLE
element.scope() is not allowed when $compileProvider.debugInfoEnabled(false);

### ISSUE THREAD

**Issue by odyss009** [angular-ui/ui-utils#376]
viewport.scope() is not allowed when $compileProvider.debugInfoEnabled(false);

https://docs.angularjs.org/guide/production

**Comment by PowerKiKi** [comment]
When creating an issue, please provide more details. Most importantly what breaks when, and what you would expect.

In this specific case, you should probably at least mention the module concerned.
