### ISSUE TITLE
opt out of placeholder masking

### ISSUE THREAD

**Issue by sean-roberts** [angular-ui/ui-utils#377]
I want to write something like this: 
`<input placeholder="Arbitrary Text" ui-mask="***-**" />`

I don't care about masking the placeholder at all, so it would be FAR more beneficial to opt out of placeholder masking period. I don't think #353 is going to help with that.

**Comment by trickpattyFH20** [comment]
+1

**Comment by PowerKiKi** [comment]
Submit a PR with tests and docs, then it will get a chance to get merged

**Comment by PowerKiKi** [comment]
UI.Utils modules was split in individuals repositories. If still valid, please consider re-submitting on its dedicated repository: https://github.com/angular-ui/ui-mask

See the [README for details](https://github.com/angular-ui/ui-utils#readme).
