### ISSUE TITLE
CHANGELOG.md v0.2.3 (2015-03-30)

### ISSUE THREAD

**Issue by julienmartin** [angular-ui/ui-utils#378]
The changelog is the same between v.0.2.2 and v.0.2.3.
What's new in v0.2.3 ?

Thanks,
Julien

**Comment by PowerKiKi** [comment]
True, looks like the changelog generation process misbehaved. Have a look at https://github.com/angular-ui/ui-utils/compare/029b428cf0bed3349750d86f2a42a2b7a5ed8c70...e913d1798e2e5b853cc366eba8cc0244bd26d30f
