### ISSUE TITLE
Dynamic mask

### ISSUE THREAD

**Issue by Bana0615** [angular-ui/ui-utils#381]
is there a way to change the mask on the fly?

**Comment by PowerKiKi** [comment]
Yes, see demo: http://angular-ui.github.io/ui-utils

**Comment by Bana0615** [comment]
I know they have it on the site as a demo but there is no code on how to do it. I have tried using a model and that doesnt update it so that is why i asked the question

**Comment by Bana0615** [comment]
I know they have it on the site as a demo but there is no code on how to do
it. I have tried using a model and that doesnt update it so that is why i
asked the question.
