### ISSUE TITLE
scrollfix does not correctly adapt to window resizing

### ISSUE THREAD

**Issue by machow** [angular-ui/ui-utils#382]
Hello,
Once scrollfix sets the ui-scrollfix class, if you move the element it is tracking (e.g. resize the window), then it doesn't correctly update.

From looking at the [source](https://github.com/angular-ui/ui-utils/blob/6f7e62339e994a944ffd988cc6f389aaa261d143/modules/scrollfix/scrollfix.js#L48), the problem seems to be that the limit based on the elements offset is calculated whenever you scroll, but this limit is only used when the ui-scrollfix class hasn't been set. The problem should be solved by using limit and not fixLimit on [line 49](https://github.com/angular-ui/ui-utils/blob/6f7e62339e994a944ffd988cc6f389aaa261d143/modules/scrollfix/scrollfix.js#L49).

Below is a minimal example of the problem. To see it

1. widen the window so the divs are side-by-side
2. scroll down so the B div turns blue (ui-scrollfix class triggered)
3. narrow the window so they are stacked
4. although the ui-scrollfix class should be added once the window goes below B, it keeps ui-scrollfix until you scroll to the top (where B was originally).

http://plnkr.co/edit/epJexRkGX9pA115Zodo0?p=preview

**Comment by PowerKiKi** [comment]
UI.Utils modules was split in individuals repositories. If still valid, please consider re-submitting the issue on its dedicated repository: https://github.com/angular-ui/ui-scrollpoint

See the [README for details](https://github.com/angular-ui/ui-utils#readme).

**Comment by PowerKiKi** [comment]
UI.Utils modules was split in individuals repositories. If still valid, please consider re-submitting the issue on its dedicated repository: https://github.com/angular-ui/ui-scrollpoint

See the [README for details](https://github.com/angular-ui/ui-utils#readme).
