### ISSUE TITLE
ui-scroll can't work well with requireJS and jQuery

### ISSUE THREAD

**Issue by HeavenGoGo** [angular-ui/ui-utils#389]
My web application use RequireJS framework to load js file on demand. 

As we known, ui-scroll have two pattern, we can use jqlite or jQuery. I create a simple sample without jQuery , if only we add the module "ui.scroll.jqlite", or use jquery, it can work well. 

But in my app, no matter I use "ui.scroll.jqlite" or use RequireJS to define jquery  it always throw an error, "TypeError: Cannot set property 'overflowY' of undefined" in createPadding function. first I just thought the answer is that I didn't set ui-scroll-viewport, but after setting, it also rose another error, can't recognize the function. once when I use script reference to load the jquery file explicitly, it work correct. 

Is there anybody run into this error?

**Comment by mfeingold** [comment]
can you provide a repro?

**Comment by HeavenGoGo** [comment]
I just create a new web application to replicate it. but have a another issue, because there is an directive named ngTagsInput, it have several directives. it will use ng-repeat load data. because the speed is slow so I use ui-scroll to speed it up. Here is the url http://1drv.ms/1QyAFr9 . 
please download and  check it. 
![ui-scroll -operation](https://cloud.githubusercontent.com/assets/11848559/7342761/33568384-eceb-11e4-99f6-0e51d0e35f52.png)
![ui-scroll -error](https://cloud.githubusercontent.com/assets/11848559/7342785/83d93482-eceb-11e4-9bf4-1193fa8f647a.png)

the error image said it can't get directive controller, if we remove the ui-scroll directive ,it can get again. 

thank you !!

**Comment by dhilt** [comment]
About your 2nd issue. It seems that you have a problem with ti-autocomplete-match directive usage. And ui-scroll is in your error stack just because of nesting ti-autocomplete-match into ui-scroll. This is a [typical error](https://docs.angularjs.org/error/$compile/ctreq), but the reason is not obvious.

By the way with your 1st issue, it looks like some kind of race conditions over sources loading. The main question is does it necessary to use require.js? I'm sure that if you choose not to use this thing, the problem will disappear... Anyway you should deal with require.js I guess.

**Comment by HeavenGoGo** [comment]
@dhilt , there are two issues in the error picture. 
(1) About the first one, as you said it is a type error, it is not obvious, no matter whether I use require or not , it will always happen, Actually this blocked me forward.
(2)About the second one, it can't access the error because there is an ng-if directive, when destroy event broadcast it will happen, it also have no relation to require.js.

**Comment by dhilt** [comment]
Okey, it seems that _ti-autocomplete-match_ doesn't have time to init all necessary high-level bindings in given configuration. As a proof I added _ng-if_ into _ti-autocomplete-match_ within your _ngTagsInput/auto-complete.html_ template:

```<ti-autocomplete-match ng-if=\"item\" data=\"item\"></ti-autocomplete-match>```

This binding-pause trick resolves "Controller can't be found" issue and the view is ok. It is just an idea... and I'm still not sure that this is _ui-scroll_ issue. The problem with JQLite (Can't read prop length og null) is still happening but the error stack (with async section) leads us to _tags-input_'s kitchen and its blur event triggering.

**Comment by HeavenGoGo** [comment]
@dhilt , thank you paying attention to  this question. I will use ng-if to as a temporary solution. I am not sure this is because tags-input, because I can't find the reason. Thanks again.

**Comment by PowerKiKi** [comment]
Actual code base of ui-scroll is in https://github.com/Hill30/NGScroller. Please re-submit your issue over there if needed.

**Comment by Alhuck** [comment]
I am using jquery-1.11.2 and not using ui-scroll-jqlite, the problem what i am facing while implementing ui-scroll is,
![ui-scroll-error](https://cloud.githubusercontent.com/assets/11574492/10488609/1be99a0e-72b7-11e5-8a52-c582e7122bb0.jpg)

if i use ui-scroll-jqlite along with jquery means also the same error exists, i can't remove jquery in my project. Why this error is happening

**Comment by dhilt** [comment]
@Alhuck It would be very nice if you could privide us with a demo of your issue (via [jsfiddle](https://jsfiddle.net/) or something else). Cause we are using jQuery+ui.scroll combination in more than one projects and have no problems with it. May be jQuery is being loaded too late?

Btw, actual code base of ui-scroll is in https://github.com/angular-ui/ui-scroll, so if you are going to provide a demo, please resubmit your issue over there.

**Comment by Alhuck** [comment]
@dhilt see to the plunker link for the further details,

http://embed.plnkr.co/TjlzuAg5Pbmf8WVdN27V/preview

why this error is happening with ui-scroll with jquery?

**Comment by dhilt** [comment]
@Alhuck hope it helps
https://github.com/angular-ui/ui-scroll/issues/28#issuecomment-148398889

**Comment by Alhuck** [comment]
Thank you @dhilt it works
