### ISSUE TITLE
ui utils build fails on Windows 7

### ISSUE THREAD

**Issue by VivekGhodekar** [angular-ui/ui-utils#391]
I have cloned ui-utils and deployed the dependencies (npm & bower install). The grunt (default) worked fine. 
The grunt serve keeps failing:

````
$ grunt serve
Running "karma:continuous" (karma) task

Running "concat:tmp" (concat) task
File "tmp/dep.js" created.

Running "concat:modules" (concat) task
File "dist/main/ui-utils.js" created.
File "dist/main/ui-utils-ieshiv.js" created.

Running "clean:rm_tmp" (clean) task
Cleaning "tmp"...OK

Running "uglify:main" (uglify) task
File "dist/main/ui-utils.min.js" created.
File "dist/main/ui-utils-ieshiv.min.js" created.

Running "concat:html_doc" (concat) task
File "demo/demos.html" created.

Running "copy:main" (copy) task
Copied 1 files

Running "build:gh-pages" (build) task
Fatal error: spawn ./node_modules/.bin/gulp ENOENT
````

Would like to understand if this is a known issue and if there is a known fix / workaround. 

Thanks.

**Comment by PowerKiKi** [comment]
This should not happen. I just tried from scratch and everything builds fine with the following tools:

````
user@machine:/tmp/ui-utils$ npm --version
1.4.28
user@machine:/tmp/ui-utils$ bower --version
1.3.12
user@machine:/tmp/ui-utils$ grunt --version
grunt-cli v0.1.13
grunt v0.4.5
````

Also see the entire log there http://pastebin.com/0E50xXSa

**Comment by PowerKiKi** [comment]
UI.Utils modules was split in individuals repositories. If still valid, please consider re-submitting the issue on its dedicated issue tracker.

See the [README for details](https://github.com/angular-ui/ui-utils#readme).
