### ISSUE TITLE
Unable to add custom data to request

### ISSUE THREAD

**Issue by zivperry** [angular-ui/ui-utils#398]
The following code:
```javascript
        // Append additional data if provided:
        if (data) {
            for (prop in data) {
                if (data.hasOwnProperty(prop)) {
                    formData.append(prop, data[prop]);
                }
            }
        }
```
Will never run since "data" is never populated.

**Comment by PowerKiKi** [comment]
Please provide more context of what is broken, why, and especially how to fix it (via a PR)

**Comment by zivperry** [comment]
ui-uploader not supported additional parameters to the upload POST request.

Variable named "data" is declared in the beginning og "ajaxUpload" function.
```javascript
function ajaxUpload(file, url) {
        var xhr, formData, prop, data = '',
            key = '' || 'file';
```
Later on in this function, there is a code that check if data not empty, to add all its properties to the formData object as request parameters (POST variables...)
```javascript
        // Append additional data if provided:
        if (data) {
            for (prop in data) {
                if (data.hasOwnProperty(prop)) {
                    formData.append(prop, data[prop]);
                }
            }
        }
```
But there is no way to populate this variable with data (the if statement in the previous example will never evaluate as "true").

As a result, the only way to add parameters to the upload request is using the query string (changing the URL) instead of using request body.

Pull request created.
