### ISSUE TITLE
ui-scroll: loading data only at last scroll bar position

### ISSUE THREAD

**Issue by RimvydasUrbonas** [angular-ui/ui-utils#405]
Hello,
if you are at page 100 and drag scroll bar to page number 20, is it possible to load data only for that last page, skipping pages in between?

**Comment by ProLoser** [comment]
That would probably mean throttling

**Comment by RimvydasUrbonas** [comment]
Yes, can we adjust throttling some how?

**Comment by PowerKiKi** [comment]
Actual code base of ui-scroll is in https://github.com/Hill30/NGScroller. Please re-submit your issue over there if needed.

**Comment by ProLoser** [comment]
@RimvydasUrbonas I would look into `_.throttle` or some sort of equivalent solution. It doesn't need to be a feature of this module.

**Comment by RimvydasUrbonas** [comment]
No this is not a throttle issue. Because even i put _.throttle on viewport.bind('scroll', _.throttle(resizeAndScrollHandler, 500)) on scroll.js, it comes back step by step from end to begining. It's a problem when I am e.x. at 900 to 1000 items range and I drag scrollbar at the beggining, so I expect jump directly to 0 to 100 range, but unfortunately scroll goes to 800 - 900 then 700-800 then 600-700 and when request takes few seconds to retrieve data it takes plenty of time to return to 0 - 100.
