### ISSUE TITLE
Please add ignore field to bower.json

### ISSUE THREAD

**Issue by ndikan** [angular-ui/ui-utils#409]
Could we please have an empty ignore field added to bower.json to keep bower happy?

Currently, you'll see the following warning from bower update:
   
    bower angular-ui-utils#bower     invalid-meta angular-ui-utils is missing "ignore" entry in bower.json 

The following will suffice:

    "ignore": [],

Some CIs will mark a build as a partial success due to this.

Thank you!

**Comment by PowerKiKi** [comment]
It is not defined as mandatory in official spec: https://github.com/bower/bower.json-spec, but if you create a PR, you'll get a chance to get it merged. However beware that ui-utils was just split in independent repositories. See README for details.
