### ISSUE TITLE
uiScroll: horizontal scrolling?

### ISSUE THREAD

**Issue by oreenge** [angular-ui/ui-utils#411]
Does uiScroll support horizontal scrolling? It doesn't appear it can do it, so I'm asking you to confirm. If it doesn't, any guidelines to implement it? I would like to contribute the solution, but want to make sure I'm starting with the right foot.

**Comment by PowerKiKi** [comment]
Actual code base of ui-scroll is in https://github.com/Hill30/NGScroller. Please re-submit your issue over there if needed.
