### ISSUE TITLE
UI-Scroll how to make the first record appear?

### ISSUE THREAD

**Issue by HeavenGoGo** [angular-ui/ui-utils#416]
in my application, assume there are 100 records, when displays data the first item is hidden, and we only can see it when scroll up. the first record should display at the beginning by default, is there anyway to implement this?

here is the screenshot of  demo sample
![scrolldemo](https://cloud.githubusercontent.com/assets/11848559/8222858/75ac5e76-15a3-11e5-9477-3b2d60c6b7aa.jpg)
actually there is an item of 0: aa: 00 on the top of 1: aa: 01.

**Comment by PowerKiKi** [comment]
Actual code base of ui-scroll is in https://github.com/Hill30/NGScroller. Please re-submit your issue over there if needed.
