### ISSUE TITLE
ui-mask: erratic behaviour when user types wrong mask (chrome 43 & firefox 38)

### ISSUE THREAD

**Issue by gerlstar** [angular-ui/ui-utils#418]
I have a mask that looks like `ui-mask="A9A 9A9" placeholder="A9A 9A9"`. Now when I first type 'M' then continually type M, the cursor moves all the way in the 2nd '9' character. Is there a way where the cursor doesnt move at all past the first M that I typed? It should focus before the 2nd character instead of focusing at the 2nd '9' character. 

Also the 'A' character changes character rapidly to 'M'. You can see an example in http://jsfiddle.net/gerlstar/norx62qn/4/

**Comment by PowerKiKi** [comment]
UI.Utils modules was split in individuals repositories. If still valid, please consider re-submitting on its dedicated repository: https://github.com/angular-ui/ui-mask

See the [README for details](https://github.com/angular-ui/ui-utils#readme).
