### ISSUE TITLE
Update bower references to use bower registry names

### ISSUE THREAD

**Issue by ProLoser** [angular-ui/ui-utils#420]
Right now the `bower.json` points directly to `angular-ui/ui-validate`, etc. Instead it should use the bower registry names like `angular-ui-validate` and should (possibly) be version locked. Not as strongly opinionated on the latter.

**Comment by PowerKiKi** [comment]
I would actually try to get rid of ui-utils altogether and convince people to user dedicated repositories instead. So I wouldn't put much time in that IMHO

**Comment by ProLoser** [comment]
I would like to keep this repo around at least for a short period to allow people to make the transition. Even https://github.com/angular-ui/angular-ui-OLDREPO is still online (for archive purposes). I would still like to just point the bower dependencies to the right place since that will make it fairly forward-compatible.
