### ISSUE TITLE
ui-jq

### ISSUE THREAD

**Issue by LeleDev** [angular-ui/ui-utils#422]
Can you please put back the ui-jq module?

It is still useful in my opinion...

**Comment by PowerKiKi** [comment]
``ui-jq`` module is still available from this repository as it used to be. If there are new patches/version of ``ui-jq``, then we might be thinking about splitting it. But if there is not a strong demand, it will be left as is.

**Comment by hmillet** [comment]
I can't find "ui-jq" module in the new release 3.0...
Which is the correct way to get it using bower ?

**Comment by PowerKiKi** [comment]
My last comment wasn't very clear. `ui-jq` is not maintained anymore, but you can still get the latest version available via:

```
bower install angular-ui-utils#jq-0.2.3
```

**Comment by hmillet** [comment]
This is clear now ;-)

Thanks
