### ISSUE TITLE
Bower install does not contain dist any more 

### ISSUE THREAD

**Issue by r00tat** [angular-ui/ui-utils#424]
Bower install does not work any more. 

Only index.js aso. are installed, but neither the source files as well as the dist files are distributed.

```
$ ls -a web-app/components/angular-ui-utils/
.           ..          .bower.json LICENSE     README.md   bower.json  index.js
```

Installed via the following bower command:

```
bower install --save angular-ui-utils
```

**Comment by r00tat** [comment]
never mind, angular-ui-utils is only index.js.

**Comment by PowerKiKi** [comment]
It is strongly advised to use individual modules instead of this legacy package. While we are not in a hurry to destroy this package, it will not be around foerever
