### ISSUE TITLE
ui.keypress  not add bower.

### ISSUE THREAD

**Issue by hetz** [angular-ui/ui-utils#426]
hi @ProLoser , when I use `bower install angular-ui-keypress --save`,bower result can't find .

so pls add to bower ,thx .

**Comment by PowerKiKi** [comment]
Use `bower install angular-ui-utils#keypress-0.2.3`

**Comment by tadeubas** [comment]
@PowerKiKi What happened with ui-utils ? version was 0.2.3, suddenly version 1.0.0 then now 3.0.0 and no keypress anymore... why ?

**Comment by ProLoser** [comment]
`ui-keypress` has been removed in favor of `ng-keypress`
