### ISSUE TITLE
Please publish all version to NPM

### ISSUE THREAD

**Issue by nmccready** [angular-ui/ui-utils#430]
Currently only 0.1.1 is on NPM. If your going to touch NPM please support it. Lastly please add a package.json file.

**Comment by PowerKiKi** [comment]
This project is dead. It's very unlikely that anything new will be ever released. Please migrate to [independent projects](https://github.com/angular-ui/ui-utils#includes) instead.

**Comment by PowerKiKi** [comment]
@tbranyen, you published this project to npm 2 years ago. Could you please either deprecate it, or give access to the following maintainers:
- https://www.npmjs.com/~proloser
- https://www.npmjs.com/~powerkik
- https://www.npmjs.com/~nmccready
