### ISSUE TITLE
ui-keypress object literal

### ISSUE THREAD

**Issue by gsklee** [angular-ui/ui-utils#47]
It is strange to write

```html
<textarea ui-keypress="{
    13: 'keypressCallback($event)'
}">
```

Should simply be

```html
<textarea ui-keypress="{
    13: keypressCallback($event)
}">
```

'keypressCallback($event)' makes it look like a string literal while in fact it is not.

**Comment by PowerKiKi** [comment]
UI.Utils modules was split in individuals repositories. If still valid, please consider re-submitting the issue on its dedicated issue tracker.

See the [README for details](https://github.com/angular-ui/ui-utils#readme).
