### ISSUE TITLE
Bug with input mask on HTC Sence with input type "tel"

### ISSUE THREAD

**Issue by fpetitit** [angular-ui/ui-utils#49]
On HTC Sence (Android 4.0.3), if input type="tel" then the behavior is very hieratic, and the input is unusable.
It seems that there is a problem with some Android devices : https://github.com/digitalBush/jquery.maskedinput/commit/905a53d55f2fd2ee0f2db1900b07172a5f68a85d 
Do you think that it could be the same cause?

Thanks

**Comment by PowerKiKi** [comment]
UI.Utils modules was split in individuals repositories. If still valid, please consider re-submitting on its dedicated repository: https://github.com/angular-ui/ui-mask

See the [README for details](https://github.com/angular-ui/ui-utils#readme).
