### ISSUE TITLE
Wiki page with upgrade instructions and version compatibility?

### ISSUE THREAD

**Issue by fabiankessler** [angular-ui/ui-utils#56]
I'm currently trying to upgrade from/to:

angular-ui 0.1.0
angularjs 1.0.4
jquery 1.9.1

angular-ui 0.3.0
angularjs 1.0.6
jquery 2.0.2

And that gives me some troubles. It would be nice if there was a wiki page with the upgrade steps. For example I've found this stackoverflow question http://stackoverflow.com/questions/12472244/how-to-integrate-angularui-to-angularjs it has a jsfiddle which doesn't work anymore, then another one that's broken too. The correct answer seems to be the last one with 0 votes (!) by durilka.

I came that far, and now realize that uiIf doesn't exist anymore (no error message). Apparently angular now has that natively, but only in newer (unstable) versions.

**Comment by PowerKiKi** [comment]
UI.Utils modules was split in individuals repositories. If still valid, please consider re-submitting the issue on its dedicated issue tracker.

See the [README for details](https://github.com/angular-ui/ui-utils#readme).
