### ISSUE TITLE
Selecting and deselecting masked textbox makes form invalid

### ISSUE THREAD

**Issue by benbenwilde** [angular-ui/ui-utils#71]
Selecting and deselecting masked textbox (input) inside a form makes the form invalid, when using ng-required.

Check out this Plunker for an example of this.
http://plnkr.co/edit/7DKExnR1cl3WyB15dSu3?p=preview

Use case: a form with masked fields that dynamically change from required to not required based on other user input.

**Comment by PowerKiKi** [comment]
UI.Utils modules was split in individuals repositories. If still valid, please consider re-submitting on its dedicated repository: https://github.com/angular-ui/ui-mask

See the [README for details](https://github.com/angular-ui/ui-utils#readme).
