### ISSUE TITLE
Mask Feature: variable length numbers

### ISSUE THREAD

**Issue by andrewt3000** [angular-ui/ui-utils#75]
I am intersted a mask feature for optional numbers.  So for example, you could have value of 9000 but show $9,000

**Comment by Voxelot** [comment]
This issue is a top ranked result by Google when searching for variable length numbers. Please include a reference to documentation that describes this behaviour for future users of this library.

**Comment by PowerKiKi** [comment]
@Voxelot please submit a PR with the documentation that would fit your need. I will merge it.
