### ISSUE TITLE
ScrollFix does not set the initial state

### ISSUE THREAD

**Issue by heliodor** [angular-ui/ui-utils#88]
The ScrollFix module binds a listener to the scroll event, but it does not set the initial state.

Instead of

$target.bind('scroll', function () {...});

I'd make it

var scrollListener = function () {...};
$target.bind('scroll', scrollListener);
scrollListener(); // sets the initial state

**Comment by PowerKiKi** [comment]
UI.Utils modules was split in individuals repositories. If still valid, please consider re-submitting the issue on its dedicated repository: https://github.com/angular-ui/ui-scrollpoint

See the [README for details](https://github.com/angular-ui/ui-utils#readme).

**Comment by heliodor** [comment]
Ok, done. https://github.com/angular-ui/ui-scrollpoint/issues/1
