### ISSUE TITLE
UI-Validate return original value when validation is failed

### ISSUE THREAD

**Issue by luke88jones** [angular-ui/ui-utils#89]
Would it be possible to add an optional attribute to the UI-validate directive to return the original field value even if the validation fails? 

The reason for this is that we have multiple validation checks against a single field and once one fails the field value is set to undefined and therefore the rest fail. I have made some changes to our local version of UI-validate (as below) and would just require the front end to have a return-invalid-value="true" flag to work. 

      var returnInvalidValue = scope.$eval(attrs.returnInvalidValue);

      angular.forEach(validateExpr, function (expression, key) {
        validateFn = function (valueToValidate) {
          if (scope.$eval(expression, { '$value' : valueToValidate })) {
            ctrl.$setValidity(key, true);
            return valueToValidate;
          } else {
            ctrl.$setValidity(key, false);
            if (returnInvalidValue){
              return valueToValidate;
            }
            else return undefined;
          }
        };
        validators[key] = validateFn;
        ctrl.$formatters.push(validateFn);
        ctrl.$parsers.push(validateFn);
      });

**Comment by PowerKiKi** [comment]
UI.Utils modules was split in individuals repositories. If still valid, please consider re-submitting on its dedicated repository: https://github.com/angular-ui/ui-validate

See the [README for details](https://github.com/angular-ui/ui-utils#readme).
