### ISSUE TITLE
Supply multiple masks as an array

### ISSUE THREAD

**Issue by solidspark** [angular-ui/ui-utils#92]
With jquery.inputmask, you can supply multiple masks as an array:

```
$('#phone').inputmask({ mask: ['999-999-9999', '+099 99 99 9999[9]']});
```

I don't see a way to do this with ui-mask. Setting an array in the ui-mask object causes the array to render as a string.

**Comment by PowerKiKi** [comment]
UI.Utils modules was split in individuals repositories. If still valid, please consider re-submitting on its dedicated repository: https://github.com/angular-ui/ui-mask

See the [README for details](https://github.com/angular-ui/ui-utils#readme).
