### ISSUE TITLE
Input with ui-mask is autofocused in IE10

### ISSUE THREAD

**Issue by coquin** [angular-ui/ui-utils#94]
`<input type="text" ui-mask="whatever" />` getting autofocused in IE10 after mask is applied.

**Comment by PowerKiKi** [comment]
UI.Utils modules was split in individuals repositories. If still valid, please consider re-submitting on its dedicated repository: https://github.com/angular-ui/ui-mask

See the [README for details](https://github.com/angular-ui/ui-utils#readme).
