### ISSUE TITLE
Angular dependencies should be more lenient

### ISSUE THREAD

**Issue by tarjei** [angular-ui/ui-utils#99]
It would be great if you defined the angularjs dependency not as ~1.0.5 but as >= 1.0.5 so that bower doesn't have problems with using this project with 1.2.x.

**Comment by PowerKiKi** [comment]
UI.Utils modules was split in individuals repositories. If still valid, please consider re-submitting the issue on its dedicated issue tracker.

See the [README for details](https://github.com/angular-ui/ui-utils#readme).
